In [156]:
import pandas as pd

from difflib import SequenceMatcher

def is_string_similar(s1: str, s2: str, threshold: float = 0.82):
    return SequenceMatcher(a=s1, b=s2).ratio() > threshold

def age_league(league, leaguexxxx, list_clubsleaguexxxx, start_index):
    list_age_league_per_year = []
    for i in range(start_index, start_index + 20):
        for x in range (20):
            if is_string_similar(s1=league['Squad'].loc[i], s2=list_clubsleaguexxxx[x]):
                list_age_league_per_year.append(leaguexxxx['age'].loc[leaguexxxx['club_name'] == list_clubsleaguexxxx[x]]) #the age of the club in list_clubsliga2004
                break

    return list_age_league_per_year

def age_bundesliga(league, leaguexxxx, list_clubsleaguexxxx, start_index):
    list_age_league_per_year = []
    for i in range(start_index, start_index + 18):
        for x in range (18):
            if is_string_similar(s1=league['Squad'].loc[i], s2=list_clubsleaguexxxx[x]):
                list_age_league_per_year.append(leaguexxxx['age'].loc[leaguexxxx['club_name'] == list_clubsleaguexxxx[x]]) #the age of the club in list_clubsliga2004
                break

    return list_age_league_per_year

liga = pd.read_csv('data/concat_years/liga.csv')

liga2004 = pd.read_csv('data/AverageAge/2004/Avg_liga2004Age.csv')
liga2005 = pd.read_csv('data/AverageAge/2005/Avg_liga2005Age.csv')
liga2006 = pd.read_csv('data/AverageAge/2006/Avg_liga2006Age.csv')
liga2007 = pd.read_csv('data/AverageAge/2007/Avg_liga2007Age.csv')
liga2008 = pd.read_csv('data/AverageAge/2008/Avg_liga2008Age.csv')
liga2009 = pd.read_csv('data/AverageAge/2009/Avg_liga2009Age.csv')
liga2010 = pd.read_csv('data/AverageAge/2010/Avg_liga2010Age.csv')
liga2011 = pd.read_csv('data/AverageAge/2011/Avg_liga2011Age.csv')
liga2012 = pd.read_csv('data/AverageAge/2012/Avg_liga2012Age.csv')
liga2013 = pd.read_csv('data/AverageAge/2013/Avg_liga2013Age.csv')
liga2014 = pd.read_csv('data/AverageAge/2014/Avg_liga2014Age.csv')
liga2015 = pd.read_csv('data/AverageAge/2015/Avg_liga2015Age.csv')
liga2016 = pd.read_csv('data/AverageAge/2016/Avg_liga2016Age.csv')
liga2017 = pd.read_csv('data/AverageAge/2017/Avg_liga2017Age.csv')
liga2018 = pd.read_csv('data/AverageAge/2018/Avg_liga2018Age.csv')
liga2019 = pd.read_csv('data/AverageAge/2019/Avg_liga2019Age.csv')
liga2020 = pd.read_csv('data/AverageAge/2020/Avg_liga2020Age.csv')

list_clubsliga2004 = liga2004['club_name'].to_list()
list_clubsliga2005 = liga2005['club_name'].to_list()
list_clubsliga2006 = liga2006['club_name'].to_list()
list_clubsliga2007 = liga2007['club_name'].to_list()
list_clubsliga2008 = liga2008['club_name'].to_list()
list_clubsliga2009 = liga2009['club_name'].to_list()
list_clubsliga2010 = liga2010['club_name'].to_list()
list_clubsliga2011 = liga2011['club_name'].to_list()
list_clubsliga2012 = liga2012['club_name'].to_list()
list_clubsliga2013 = liga2013['club_name'].to_list()
list_clubsliga2014 = liga2014['club_name'].to_list()
list_clubsliga2015 = liga2015['club_name'].to_list()
list_clubsliga2016 = liga2016['club_name'].to_list()
list_clubsliga2017 = liga2017['club_name'].to_list()
list_clubsliga2018 = liga2018['club_name'].to_list()
list_clubsliga2019 = liga2019['club_name'].to_list()
list_clubsliga2020 = liga2020['club_name'].to_list()

list_age_liga = []

list_age_liga.append(age_league(liga, liga2004, list_clubsliga2004, 0))
list_age_liga.append(age_league(liga, liga2005, list_clubsliga2005, 20))
list_age_liga.append(age_league(liga, liga2006, list_clubsliga2006, 40))
list_age_liga.append(age_league(liga, liga2007, list_clubsliga2007, 60))
list_age_liga.append(age_league(liga, liga2008, list_clubsliga2008, 80))
list_age_liga.append(age_league(liga, liga2009, list_clubsliga2009, 100))
list_age_liga.append(age_league(liga, liga2010, list_clubsliga2010, 120))
list_age_liga.append(age_league(liga, liga2011, list_clubsliga2011, 140))
list_age_liga.append(age_league(liga, liga2012, list_clubsliga2012, 160))
list_age_liga.append(age_league(liga, liga2013, list_clubsliga2013, 180))
list_age_liga.append(age_league(liga, liga2014, list_clubsliga2014, 200))
list_age_liga.append(age_league(liga, liga2015, list_clubsliga2015, 220))
list_age_liga.append(age_league(liga, liga2016, list_clubsliga2016, 240))
list_age_liga.append(age_league(liga, liga2017, list_clubsliga2017, 260))
list_age_liga.append(age_league(liga, liga2018, list_clubsliga2018, 280))
list_age_liga.append(age_league(liga, liga2019, list_clubsliga2019, 300))
list_age_liga.append(age_league(liga, liga2020, list_clubsliga2020, 320))

print(list_age_liga)

#list => faire de list_age_liga pas une liste de liste, mais une seule liste avec une fonction...
#liga['Age'] = list
#liga.to_csv('data/concat_years_age/liga.csv', index=False)

[[6    27.0
Name: age, dtype: float64, 14    24.952381
Name: age, dtype: float64, 19    24.611111
Name: age, dtype: float64, 13    27.45
Name: age, dtype: float64, 10    26.529412
Name: age, dtype: float64, 17    24.111111
Name: age, dtype: float64, 18    23.828571
Name: age, dtype: float64, 1    22.222222
Name: age, dtype: float64, 5    28.346154
Name: age, dtype: float64, 9    26.2
Name: age, dtype: float64, 2    25.456522
Name: age, dtype: float64, 16    26.92
Name: age, dtype: float64, 7    26.48
Name: age, dtype: float64, 15    24.4
Name: age, dtype: float64, 3    25.818182
Name: age, dtype: float64, 12    24.866667
Name: age, dtype: float64, 11    26.315789
Name: age, dtype: float64, 8    27.217391
Name: age, dtype: float64, 4    26.235294
Name: age, dtype: float64, 0    25.368421
Name: age, dtype: float64], [7    24.647059
Name: age, dtype: float64, 14    24.192308
Name: age, dtype: float64, 18    23.928571
Name: age, dtype: float64, 2    26.625
Name: age, dtype: float64, 17    26.416667
Name: age, dtype: float64, 3    25.612903
Name: age, dtype: float64, 19    23.555556
Name: age, dtype: float64, 6    26.0
Name: age, dtype: float64, 8    25.592593
Name: age, dtype: float64, 1    25.157895
Name: age, dtype: float64, 16    25.541667
Name: age, dtype: float64, 0    23.666667
Name: age, dtype: float64, 11    26.069767
Name: age, dtype: float64, 13    26.833333
Name: age, dtype: float64, 10    25.625
Name: age, dtype: float64, 15    25.36
Name: age, dtype: float64, 12    25.078947
Name: age, dtype: float64, 5    25.25
Name: age, dtype: float64, 4    26.277778
Name: age, dtype: float64, 9    25.033333
Name: age, dtype: float64], [13    24.733333
Name: age, dtype: float64, 5    27.5
Name: age, dtype: float64, 17    25.115385
Name: age, dtype: float64, 18    25.944444
Name: age, dtype: float64, 19    25.115385
Name: age, dtype: float64, 15    26.333333
Name: age, dtype: float64, 1    24.926829
Name: age, dtype: float64, 16    26.323529
Name: age, dtype: float64, 6    26.192308
Name: age, dtype: float64, 11    25.6875
Name: age, dtype: float64, 9    25.541667
Name: age, dtype: float64, 10    25.088235
Name: age, dtype: float64, 4    25.456522
Name: age, dtype: float64, 2    24.307692
Name: age, dtype: float64, 8    28.206897
Name: age, dtype: float64, 12    26.0
Name: age, dtype: float64, 0    24.272727
Name: age, dtype: float64, 3    25.48
Name: age, dtype: float64, 14    25.931034
Name: age, dtype: float64, 7    26.976744
Name: age, dtype: float64], [11    24.973684
Name: age, dtype: float64, 19    24.043478
Name: age, dtype: float64, 4    24.166667
Name: age, dtype: float64, 1    24.029412
Name: age, dtype: float64, 16    25.371429
Name: age, dtype: float64, 9    23.871795
Name: age, dtype: float64, 8    24.416667
Name: age, dtype: float64, 17    25.774194
Name: age, dtype: float64, 3    23.642857
Name: age, dtype: float64, 18    23.906977
Name: age, dtype: float64, 0    26.6
Name: age, dtype: float64, 7    25.04
Name: age, dtype: float64, 10    27.192308
Name: age, dtype: float64, 5    23.68
Name: age, dtype: float64, 13    25.4
Name: age, dtype: float64, 15    26.25641
Name: age, dtype: float64, 2    23.53125
Name: age, dtype: float64, 14    25.903226
Name: age, dtype: float64, 12    26.771429
Name: age, dtype: float64, 6    28.377778
Name: age, dtype: float64], [5    25.714286
Name: age, dtype: float64, 12    23.217391
Name: age, dtype: float64, 15    25.6
Name: age, dtype: float64, 1    24.206897
Name: age, dtype: float64, 19    23.823529
Name: age, dtype: float64, 18    24.488372
Name: age, dtype: float64, 4    24.285714
Name: age, dtype: float64, 7    26.935484
Name: age, dtype: float64, 9    25.675676
Name: age, dtype: float64, 8    25.0
Name: age, dtype: float64, 17    25.608696
Name: age, dtype: float64, 10    24.057143
Name: age, dtype: float64, 0    26.909091
Name: age, dtype: float64, 16    24.833333
Name: age, dtype: float64, 2    24.178571
Name: age, dtype: float64, 13    25.423077
Name: age, dtype: float64, 6    24.5
Name: age, dtype: float64, 11    27.259259
Name: age, dtype: float64, 3    26.52
Name: age, dtype: float64, 14    24.633333
Name: age, dtype: float64], [5    24.333333
Name: age, dtype: float64, 11    25.5
Name: age, dtype: float64, 17    24.823529
Name: age, dtype: float64, 14    26.428571
Name: age, dtype: float64, 9    24.344828
Name: age, dtype: float64, 6    25.791667
Name: age, dtype: float64, 18    24.653846
Name: age, dtype: float64, 0    25.611111
Name: age, dtype: float64, 1    24.733333
Name: age, dtype: float64, 4    25.692308
Name: age, dtype: float64, 8    24.285714
Name: age, dtype: float64, 2    24.88
Name: age, dtype: float64, 16    25.157895
Name: age, dtype: float64, 13    26.722222
Name: age, dtype: float64, 15    25.631579
Name: age, dtype: float64, 10    23.871795
Name: age, dtype: float64, 7    25.804878
Name: age, dtype: float64, 12    24.789474
Name: age, dtype: float64, 3    24.428571
Name: age, dtype: float64, 19    24.222222
Name: age, dtype: float64], [4    25.277778
Name: age, dtype: float64, 12    26.153846
Name: age, dtype: float64, 18    25.5625
Name: age, dtype: float64, 19    25.25
Name: age, dtype: float64, 15    24.78125
Name: age, dtype: float64, 0    25.047619
Name: age, dtype: float64, 1    23.681818
Name: age, dtype: float64, 9    24.918919
Name: age, dtype: float64, 2    25.227273
Name: age, dtype: float64, 16    25.833333
Name: age, dtype: float64, 8    24.851064
Name: age, dtype: float64, 11    24.774194
Name: age, dtype: float64, 14    26.235294
Name: age, dtype: float64, 7    27.214286
Name: age, dtype: float64, 13    24.842105
Name: age, dtype: float64, 5    26.05
Name: age, dtype: float64, 10    24.621622
Name: age, dtype: float64, 3    26.033333
Name: age, dtype: float64, 6    26.833333
Name: age, dtype: float64, 17    24.115385
Name: age, dtype: float64], [13    24.692308
Name: age, dtype: float64, 3    24.958333
Name: age, dtype: float64, 18    25.129032
Name: age, dtype: float64, 7    25.375
Name: age, dtype: float64, 1    23.195122
Name: age, dtype: float64, 6    26.388889
Name: age, dtype: float64, 2    25.766667
Name: age, dtype: float64, 9    25.625
Name: age, dtype: float64, 16    24.394737
Name: age, dtype: float64, 0    24.846154
Name: age, dtype: float64, 4    25.088235
Name: age, dtype: float64, 14    24.666667
Name: age, dtype: float64, 12    26.62069
Name: age, dtype: float64, 8    24.921053
Name: age, dtype: float64, 11    25.294118
Name: age, dtype: float64, 15    26.292683
Name: age, dtype: float64, 5    24.606061
Name: age, dtype: float64, 19    25.666667
Name: age, dtype: float64, 17    25.6875
Name: age, dtype: float64, 10    23.857143
Name: age, dtype: float64], [5    23.5
Name: age, dtype: float64, 14    25.466667
Name: age, dtype: float64, 1    24.766667
Name: age, dtype: float64, 15    24.75
Name: age, dtype: float64, 19    26.04
Name: age, dtype: float64, 9    26.96875
Name: age, dtype: float64, 13    24.866667
Name: age, dtype: float64, 12    25.625
Name: age, dtype: float64, 18    25.933333
Name: age, dtype: float64, 6    25.566667
Name: age, dtype: float64, 8    26.926829
Name: age, dtype: float64, 0    27.0
Name: age, dtype: float64, 10    24.16129
Name: age, dtype: float64, 16    26.086957
Name: age, dtype: float64, 7    24.917647
Name: age, dtype: float64, 2    26.588235
Name: age, dtype: float64, 3    26.347826
Name: age, dtype: float64, 11    24.724138
Name: age, dtype: float64, 4    26.846154
Name: age, dtype: float64, 17    25.906977
Name: age, dtype: float64], [1    24.289474
Name: age, dtype: float64, 5    23.0
Name: age, dtype: float64, 13    24.666667
Name: age, dtype: float64, 0    24.583333
Name: age, dtype: float64, 16    24.854545
Name: age, dtype: float64, 19    26.741935
Name: age, dtype: float64, 14    25.833333
Name: age, dtype: float64, 18    25.965517
Name: age, dtype: float64, 3    25.852941
Name: age, dtype: float64, 8    28.0
Name: age, dtype: float64, 9    25.536585
Name: age, dtype: float64, 11    25.837838
Name: age, dtype: float64, 6    25.875
Name: age, dtype: float64, 10    23.62069
Name: age, dtype: float64, 7    24.611111
Name: age, dtype: float64, 4    26.090909
Name: age, dtype: float64, 17    26.066667
Name: age, dtype: float64, 2    27.074074
Name: age, dtype: float64, 15    24.736842
Name: age, dtype: float64, 12    24.767442
Name: age, dtype: float64], [6    25.535714
Name: age, dtype: float64, 13    24.875
Name: age, dtype: float64, 1    25.040816
Name: age, dtype: float64, 18    25.125
Name: age, dtype: float64, 16    25.0
Name: age, dtype: float64, 19    24.137931
Name: age, dtype: float64, 0    22.45
Name: age, dtype: float64, 2    26.0
Name: age, dtype: float64, 10    25.888889
Name: age, dtype: float64, 11    24.5625
Name: age, dtype: float64, 12    25.130435
Name: age, dtype: float64, 14    24.75
Name: age, dtype: float64, 5    25.939394
Name: age, dtype: float64, 9    27.071429
Name: age, dtype: float64, 7    26.681818
Name: age, dtype: float64, 4    24.833333
Name: age, dtype: float64, 8    24.810127
Name: age, dtype: float64, 15    26.461538
Name: age, dtype: float64, 17    25.484848
Name: age, dtype: float64, 3    25.319149
Name: age, dtype: float64], [4    24.190476
Name: age, dtype: float64, 12    23.272727
Name: age, dtype: float64, 1    24.244444
Name: age, dtype: float64, 19    25.324324
Name: age, dtype: float64, 0    23.862069
Name: age, dtype: float64, 2    25.818182
Name: age, dtype: float64, 15    26.295455
Name: age, dtype: float64, 8    25.325
Name: age, dtype: float64, 13    24.866667
Name: age, dtype: float64, 11    25.05
Name: age, dtype: float64, 17    26.242424
Name: age, dtype: float64, 18    23.888889
Name: age, dtype: float64, 9    24.813953
Name: age, dtype: float64, 14    25.777778
Name: age, dtype: float64, 3    25.947368
Name: age, dtype: float64, 6    24.65
Name: age, dtype: float64, 16    23.6875
Name: age, dtype: float64, 10    26.142857
Name: age, dtype: float64, 5    26.076923
Name: age, dtype: float64, 7    27.225806
Name: age, dtype: float64], [12    22.192308
Name: age, dtype: float64, 7    24.708333
Name: age, dtype: float64, 1    23.325581
Name: age, dtype: float64, 15    25.972222
Name: age, dtype: float64, 19    23.4
Name: age, dtype: float64, 13    23.96
Name: age, dtype: float64, 0    24.5
Name: age, dtype: float64, 10    25.595238
Name: age, dtype: float64, 5    26.405405
Name: age, dtype: float64, 14    24.906977
Name: age, dtype: float64, 9    25.514286
Name: age, dtype: float64, 18    24.970588
Name: age, dtype: float64, 4    23.666667
Name: age, dtype: float64, 17    26.032258
Name: age, dtype: float64, 11    25.777778
Name: age, dtype: float64, 6    26.106383
Name: age, dtype: float64, 3    25.731707
Name: age, dtype: float64, 16    25.1
Name: age, dtype: float64, 2    26.833333
Name: age, dtype: float64, 8    24.792208
Name: age, dtype: float64], [6    25.0
Name: age, dtype: float64, 1    24.210526
Name: age, dtype: float64, 13    22.947368
Name: age, dtype: float64, 18    25.782609
Name: age, dtype: float64, 19    24.090909
Name: age, dtype: float64, 12    26.604651
Name: age, dtype: float64, 16    26.4375
Name: age, dtype: float64, 7    27.14
Name: age, dtype: float64, 15    24.833333
Name: age, dtype: float64, 8    25.357143
Name: age, dtype: float64, 11    27.323529
Name: age, dtype: float64, 14    25.107143
Name: age, dtype: float64, 3    24.228571
Name: age, dtype: float64, 4    23.904762
Name: age, dtype: float64, 9    25.1
Name: age, dtype: float64, 0    25.0
Name: age, dtype: float64, 2    25.511628
Name: age, dtype: float64, 5    26.725
Name: age, dtype: float64, 17    26.088889
Name: age, dtype: float64, 10    26.2
Name: age, dtype: float64], [5    24.236842
Name: age, dtype: float64, 1    23.75
Name: age, dtype: float64, 12    22.633333
Name: age, dtype: float64, 18    24.659091
Name: age, dtype: float64, 6    26.25
Name: age, dtype: float64, 17    24.714286
Name: age, dtype: float64, 9    26.0
Name: age, dtype: float64, 0    25.3
Name: age, dtype: float64, 13    25.615385
Name: age, dtype: float64, 11    25.820513
Name: age, dtype: float64, 4    24.52
Name: age, dtype: float64, 15    26.0
Name: age, dtype: float64, 2    24.754386
Name: age, dtype: float64, 19    25.0
Name: age, dtype: float64, 8    25.410256
Name: age, dtype: float64, 14    24.069767
Name: age, dtype: float64, 3    24.512195
Name: age, dtype: float64, 7    24.909091
Name: age, dtype: float64, 16    26.044444
Name: age, dtype: float64, 10    26.127273
Name: age, dtype: float64], [13    22.222222
Name: age, dtype: float64, 6    23.727273
Name: age, dtype: float64, 1    24.325
Name: age, dtype: float64, 17    25.269841
Name: age, dtype: float64, 19    26.0
Name: age, dtype: float64, 14    23.888889
Name: age, dtype: float64, 8    25.567568
Name: age, dtype: float64, 7    26.5
Name: age, dtype: float64, 18    24.422222
Name: age, dtype: float64, 2    25.459459
Name: age, dtype: float64, 0    25.818182
Name: age, dtype: float64, 9    25.595238
Name: age, dtype: float64, 15    24.209302
Name: age, dtype: float64, 16    25.222222
Name: age, dtype: float64, 12    24.775
Name: age, dtype: float64, 5    24.740741
Name: age, dtype: float64, 4    25.657143
Name: age, dtype: float64, 3    24.2
Name: age, dtype: float64, 11    24.533333
Name: age, dtype: float64, 10    25.878788
Name: age, dtype: float64], [1    24.777778
Name: age, dtype: float64, 12    22.294118
Name: age, dtype: float64, 7    23.117647
Name: age, dtype: float64, 17    25.487805
Name: age, dtype: float64, 13    26.5
Name: age, dtype: float64, 11    24.733333
Name: age, dtype: float64, 19    24.818182
Name: age, dtype: float64, 3    25.863636
Name: age, dtype: float64, 9    25.653846
Name: age, dtype: float64, 0    23.857143
Name: age, dtype: float64, 2    26.366667
Name: age, dtype: float64, 4    25.983607
Name: age, dtype: float64, 18    24.62963
Name: age, dtype: float64, 10    24.965517
Name: age, dtype: float64, 8    25.222222
Name: age, dtype: float64, 5    24.622222
Name: age, dtype: float64, 6    27.684211
Name: age, dtype: float64, 16    24.923077
Name: age, dtype: float64, 14    25.269231
Name: age, dtype: float64, 15    26.5
Name: age, dtype: float64]]

In [145]:
PL = pd.read_csv('data/concat_years/PL.csv')

PL2004 = pd.read_csv('data/AverageAge/2004/Avg_PL2004Age.csv')
PL2005 = pd.read_csv('data/AverageAge/2005/Avg_PL2005Age.csv')
PL2006 = pd.read_csv('data/AverageAge/2006/Avg_PL2006Age.csv')
PL2007 = pd.read_csv('data/AverageAge/2007/Avg_PL2007Age.csv')
PL2008 = pd.read_csv('data/AverageAge/2008/Avg_PL2008Age.csv')
PL2009 = pd.read_csv('data/AverageAge/2009/Avg_PL2009Age.csv')
PL2010 = pd.read_csv('data/AverageAge/2010/Avg_PL2010Age.csv')
PL2011 = pd.read_csv('data/AverageAge/2011/Avg_PL2011Age.csv')
PL2012 = pd.read_csv('data/AverageAge/2012/Avg_PL2012Age.csv')
PL2013 = pd.read_csv('data/AverageAge/2013/Avg_PL2013Age.csv')
PL2014 = pd.read_csv('data/AverageAge/2014/Avg_PL2014Age.csv')
PL2015 = pd.read_csv('data/AverageAge/2015/Avg_PL2015Age.csv')
PL2016 = pd.read_csv('data/AverageAge/2016/Avg_PL2016Age.csv')
PL2017 = pd.read_csv('data/AverageAge/2017/Avg_PL2017Age.csv')
PL2018 = pd.read_csv('data/AverageAge/2018/Avg_PL2018Age.csv')
PL2019 = pd.read_csv('data/AverageAge/2019/Avg_PL2019Age.csv')
PL2020 = pd.read_csv('data/AverageAge/2020/Avg_PL2020Age.csv')

list_clubsPL2004 = PL2004['club_name'].to_list()
list_clubsPL2005 = PL2005['club_name'].to_list()
list_clubsPL2006 = PL2006['club_name'].to_list()
list_clubsPL2007 = PL2007['club_name'].to_list()
list_clubsPL2008 = PL2008['club_name'].to_list()
list_clubsPL2009 = PL2009['club_name'].to_list()
list_clubsPL2010 = PL2010['club_name'].to_list()
list_clubsPL2011 = PL2011['club_name'].to_list()
list_clubsPL2012 = PL2012['club_name'].to_list()
list_clubsPL2013 = PL2013['club_name'].to_list()
list_clubsPL2014 = PL2014['club_name'].to_list()
list_clubsPL2015 = PL2015['club_name'].to_list()
list_clubsPL2016 = PL2016['club_name'].to_list()
list_clubsPL2017 = PL2017['club_name'].to_list()
list_clubsPL2018 = PL2018['club_name'].to_list()
list_clubsPL2019 = PL2019['club_name'].to_list()
list_clubsPL2020 = PL2020['club_name'].to_list()

list_age_PL = []

list_age_PL.append(age_league(PL, PL2004, list_clubsPL2004, 0))
list_age_PL.append(age_league(PL, PL2005, list_clubsPL2005, 20))
list_age_PL.append(age_league(PL, PL2006, list_clubsPL2006, 40))
list_age_PL.append(age_league(PL, PL2007, list_clubsPL2007, 60))
list_age_PL.append(age_league(PL, PL2008, list_clubsPL2008, 80))
list_age_PL.append(age_league(PL, PL2009, list_clubsPL2009, 100))
list_age_PL.append(age_league(PL, PL2010, list_clubsPL2010, 120))
list_age_PL.append(age_league(PL, PL2011, list_clubsPL2011, 140))
list_age_PL.append(age_league(PL, PL2012, list_clubsPL2012, 160))
list_age_PL.append(age_league(PL, PL2013, list_clubsPL2013, 180))
list_age_PL.append(age_league(PL, PL2014, list_clubsPL2014, 200))
list_age_PL.append(age_league(PL, PL2015, list_clubsPL2015, 220))
list_age_PL.append(age_league(PL, PL2016, list_clubsPL2016, 240))
list_age_PL.append(age_league(PL, PL2017, list_clubsPL2017, 260))
list_age_PL.append(age_league(PL, PL2018, list_clubsPL2018, 280))
list_age_PL.append(age_league(PL, PL2019, list_clubsPL2019, 300))
list_age_PL.append(age_league(PL, PL2020, list_clubsPL2020, 320))

print(list_age_PL)

#list => faire de list_age_PL pas une liste de liste, mais une seule liste avec une fonction...
#PL['Age'] = list
#PL.to_csv('data/concat_years_age/PL.csv', index=False)

[[6    24.521739
Name: age, dtype: float64, 0    22.829268
Name: age, dtype: float64, 12    21.846154
Name: age, dtype: float64, 8    25.0
Name: age, dtype: float64, 10    22.837209
Name: age, dtype: float64, 13    24.069767
Name: age, dtype: float64, 11    24.722222
Name: age, dtype: float64, 18    23.485714
Name: age, dtype: float64, 1    22.290323
Name: age, dtype: float64, 5    24.527778
Name: age, dtype: float64, 2    24.42
Name: age, dtype: float64, 9    23.021277
Name: age, dtype: float64, 14    23.722222
Name: age, dtype: float64, 3    25.285714
Name: age, dtype: float64, 16    24.47619
Name: age, dtype: float64, 19    24.829268
Name: age, dtype: float64, 7    24.818182
Name: age, dtype: float64, 15    25.424242
Name: age, dtype: float64, 17    23.262295
Name: age, dtype: float64], [6    23.333333
Name: age, dtype: float64, 11    21.882353
Name: age, dtype: float64, 9    22.711538
Name: age, dtype: float64, 0    21.108108
Name: age, dtype: float64, 16    22.215686
Name: age, dtype: float64, 3    21.416667
Name: age, dtype: float64, 13    24.28125
Name: age, dtype: float64, 18    23.032258
Name: age, dtype: float64, 19    26.542857
Name: age, dtype: float64, 7    23.827586
Name: age, dtype: float64, 8    24.5625
Name: age, dtype: float64, 5    23.188679
Name: age, dtype: float64, 12    22.066667
Name: age, dtype: float64, 10    23.44
Name: age, dtype: float64, 1    22.645161
Name: age, dtype: float64, 14    24.378378
Name: age, dtype: float64, 2    22.241379
Name: age, dtype: float64, 17    25.181818
Name: age, dtype: float64, 15    23.55102
Name: age, dtype: float64], [10    21.244898
Name: age, dtype: float64, 5    23.714286
Name: age, dtype: float64, 8    22.055556
Name: age, dtype: float64, 0    22.085714
Name: age, dtype: float64, 16    23.27907
Name: age, dtype: float64, 6    23.464286
Name: age, dtype: float64, 14    21.0
Name: age, dtype: float64, 13    24.762712
Name: age, dtype: float64, 2    23.627451
Name: age, dtype: float64, 1    25.888889
Name: age, dtype: float64, 11    24.522727
Name: age, dtype: float64, 12    25.208333
Name: age, dtype: float64, 9    24.97619
Name: age, dtype: float64, 18    24.136364
Name: age, dtype: float64, 7    25.214286
Name: age, dtype: float64, 19    26.510638
Name: age, dtype: float64, 15    24.434211
Name: age, dtype: float64, 4    22.764706
Name: age, dtype: float64, 17    21.636364
Name: age, dtype: float64], [11    21.553191
Name: age, dtype: float64, 5    21.388889
Name: age, dtype: float64, 0    20.828571
Name: age, dtype: float64, 9    21.563636
Name: age, dtype: float64, 7    24.4375
Name: age, dtype: float64, 1    23.814815
Name: age, dtype: float64, 3    22.081081
Name: age, dtype: float64, 14    23.173077
Name: age, dtype: float64, 10    23.666667
Name: age, dtype: float64, 18    24.925
Name: age, dtype: float64, 17    21.75
Name: age, dtype: float64, 13    24.972222
Name: age, dtype: float64, 12    23.0
Name: age, dtype: float64, 19    25.891304
Name: age, dtype: float64, 16    25.886792
Name: age, dtype: float64, 8    25.878788
Name: age, dtype: float64, 15    20.826667
Name: age, dtype: float64, 2    22.241379
Name: age, dtype: float64, 6    26.413793
Name: age, dtype: float64], [10    21.289474
Name: age, dtype: float64, 8    21.561404
Name: age, dtype: float64, 4    24.25
Name: age, dtype: float64, 0    21.285714
Name: age, dtype: float64, 5    23.625
Name: age, dtype: float64, 1    24.676471
Name: age, dtype: float64, 6    25.455882
Name: age, dtype: float64, 16    22.458333
Name: age, dtype: float64, 18    24.25
Name: age, dtype: float64, 9    23.454545
Name: age, dtype: float64, 19    24.163265
Name: age, dtype: float64, 14    23.647059
Name: age, dtype: float64, 13    22.886792
Name: age, dtype: float64, 2    22.960784
Name: age, dtype: float64, 15    24.544118
Name: age, dtype: float64, 7    27.75
Name: age, dtype: float64, 12    22.216216
Name: age, dtype: float64, 11    22.416667
Name: age, dtype: float64, 17    23.878049
Name: age, dtype: float64], [6    22.178571
Name: age, dtype: float64, 12    21.219512
Name: age, dtype: float64, 0    21.074074
Name: age, dtype: float64, 16    21.378788
Name: age, dtype: float64, 11    24.22
Name: age, dtype: float64, 1    24.081081
Name: age, dtype: float64, 10    22.543478
Name: age, dtype: float64, 7    23.935484
Name: age, dtype: float64, 2    23.851852
Name: age, dtype: float64, 3    22.635135
Name: age, dtype: float64, 14    23.916667
Name: age, dtype: float64, 8    24.215686
Name: age, dtype: float64, 15    25.25
Name: age, dtype: float64, 19    23.0
Name: age, dtype: float64, 18    24.75
Name: age, dtype: float64, 17    24.24
Name: age, dtype: float64, 5    22.115385
Name: age, dtype: float64, 9    24.377778
Name: age, dtype: float64, 13    24.268657
Name: age, dtype: float64], [11    21.045455
Name: age, dtype: float64, 6    21.725
Name: age, dtype: float64, 10    23.084746
Name: age, dtype: float64, 0    22.238095
Name: age, dtype: float64, 15    21.422535
Name: age, dtype: float64, 9    23.571429
Name: age, dtype: float64, 7    23.346154
Name: age, dtype: float64, 8    24.842105
Name: age, dtype: float64, 1    23.9
Name: age, dtype: float64, 14    24.096774
Name: age, dtype: float64, 16    24.0
Name: age, dtype: float64, 12    23.142857
Name: age, dtype: float64, 13    25.595745
Name: age, dtype: float64, 3    23.017241
Name: age, dtype: float64, 18    24.636364
Name: age, dtype: float64, 19    22.928571
Name: age, dtype: float64, 2    24.466667
Name: age, dtype: float64, 4    24.62
Name: age, dtype: float64, 17    24.459459
Name: age, dtype: float64], [8    23.171875
Name: age, dtype: float64, 9    22.914286
Name: age, dtype: float64, 0    23.118644
Name: age, dtype: float64, 16    23.479452
Name: age, dtype: float64, 10    22.381818
Name: age, dtype: float64, 4    21.522727
Name: age, dtype: float64, 5    23.972222
Name: age, dtype: float64, 7    23.675
Name: age, dtype: float64, 6    25.5
Name: age, dtype: float64, 17    24.254902
Name: age, dtype: float64, 15    24.813953
Name: age, dtype: float64, 11    22.315789
Name: age, dtype: float64, 14    23.462687
Name: age, dtype: float64, 13    24.615385
Name: age, dtype: float64, 18    22.973684
Name: age, dtype: float64, 1    24.73913
Name: age, dtype: float64, 12    25.057471
Name: age, dtype: float64, 2    23.181818
Name: age, dtype: float64, 19    22.854839
Name: age, dtype: float64], [7    22.424242
Name: age, dtype: float64, 6    22.98
Name: age, dtype: float64, 2    21.105263
Name: age, dtype: float64, 0    22.972973
Name: age, dtype: float64, 16    24.0
Name: age, dtype: float64, 3    23.461538
Name: age, dtype: float64, 5    23.108108
Name: age, dtype: float64, 17    23.647059
Name: age, dtype: float64, 15    24.738095
Name: age, dtype: float64, 18    25.115385
Name: age, dtype: float64, 9    24.272727
Name: age, dtype: float64, 4    24.517857
Name: age, dtype: float64, 13    26.531915
Name: age, dtype: float64, 12    25.0
Name: age, dtype: float64, 1    24.419355
Name: age, dtype: float64, 8    22.095238
Name: age, dtype: float64, 14    23.75
Name: age, dtype: float64, 19    22.613636
Name: age, dtype: float64, 11    22.816667
Name: age, dtype: float64, 10    25.364706
Name: age, dtype: float64], [9    24.5
Name: age, dtype: float64, 8    22.146341
Name: age, dtype: float64, 3    21.918919
Name: age, dtype: float64, 0    23.454545
Name: age, dtype: float64, 5    23.526316
Name: age, dtype: float64, 17    23.719298
Name: age, dtype: float64, 10    21.736842
Name: age, dtype: float64, 13    24.512195
Name: age, dtype: float64, 14    25.525
Name: age, dtype: float64, 11    22.30303
Name: age, dtype: float64, 4    24.037975
Name: age, dtype: float64, 16    24.073171
Name: age, dtype: float64, 19    25.0
Name: age, dtype: float64, 15    23.072464
Name: age, dtype: float64, 1    24.016129
Name: age, dtype: float64, 7    24.723077
Name: age, dtype: float64, 18    26.032258
Name: age, dtype: float64, 12    24.232558
Name: age, dtype: float64, 6    24.796875
Name: age, dtype: float64, 2    23.564516
Name: age, dtype: float64], [3    22.977778
Name: age, dtype: float64, 9    24.275862
Name: age, dtype: float64, 0    23.35
Name: age, dtype: float64, 10    23.660377
Name: age, dtype: float64, 17    23.25
Name: age, dtype: float64, 8    22.456522
Name: age, dtype: float64, 13    25.326531
Name: age, dtype: float64, 16    24.313725
Name: age, dtype: float64, 14    24.225
Name: age, dtype: float64, 4    25.345238
Name: age, dtype: float64, 5    22.46875
Name: age, dtype: float64, 19    23.339286
Name: age, dtype: float64, 18    26.342857
Name: age, dtype: float64, 7    25.232143
Name: age, dtype: float64, 11    22.653061
Name: age, dtype: float64, 15    24.519231
Name: age, dtype: float64, 1    23.459016
Name: age, dtype: float64, 6    23.3
Name: age, dtype: float64, 2    23.553191
Name: age, dtype: float64, 12    23.929577
Name: age, dtype: float64], [6    25.068966
Name: age, dtype: float64, 1    23.296296
Name: age, dtype: float64, 16    24.625
Name: age, dtype: float64, 8    23.0
Name: age, dtype: float64, 9    23.642857
Name: age, dtype: float64, 12    24.5
Name: age, dtype: float64, 19    24.218182
Name: age, dtype: float64, 7    22.895833
Name: age, dtype: float64, 13    26.096774
Name: age, dtype: float64, 3    22.973684
Name: age, dtype: float64, 5    24.028571
Name: age, dtype: float64, 15    23.659091
Name: age, dtype: float64, 17    25.444444
Name: age, dtype: float64, 18    27.08
Name: age, dtype: float64, 4    24.522727
Name: age, dtype: float64, 0    24.318841
Name: age, dtype: float64, 14    25.666667
Name: age, dtype: float64, 10    23.163265
Name: age, dtype: float64, 11    24.619048
Name: age, dtype: float64, 2    25.032787
Name: age, dtype: float64], [3    23.912281
Name: age, dtype: float64, 16    23.625
Name: age, dtype: float64, 9    23.666667
Name: age, dtype: float64, 8    23.9
Name: age, dtype: float64, 1    23.791667
Name: age, dtype: float64, 10    23.478261
Name: age, dtype: float64, 5    25.675676
Name: age, dtype: float64, 12    25.285714
Name: age, dtype: float64, 0    23.836735
Name: age, dtype: float64, 18    26.074074
Name: age, dtype: float64, 19    23.789474
Name: age, dtype: float64, 7    25.028571
Name: age, dtype: float64, 13    25.538462
Name: age, dtype: float64, 4    24.934783
Name: age, dtype: float64, 15    25.473684
Name: age, dtype: float64, 2    24.339623
Name: age, dtype: float64, 17    24.672131
Name: age, dtype: float64, 6    25.121951
Name: age, dtype: float64, 11    25.842105
Name: age, dtype: float64, 14    26.229167
Name: age, dtype: float64], [10    23.828125
Name: age, dtype: float64, 11    23.5
Name: age, dtype: float64, 16    23.08
Name: age, dtype: float64, 9    23.551724
Name: age, dtype: float64, 4    23.267606
Name: age, dtype: float64, 1    25.178571
Name: age, dtype: float64, 3    25.410256
Name: age, dtype: float64, 6    24.302326
Name: age, dtype: float64, 8    25.851852
Name: age, dtype: float64, 12    24.410714
Name: age, dtype: float64, 5    23.787879
Name: age, dtype: float64, 0    25.275862
Name: age, dtype: float64, 19    24.658537
Name: age, dtype: float64, 17    25.33871
Name: age, dtype: float64, 2    25.133333
Name: age, dtype: float64, 7    24.512195
Name: age, dtype: float64, 13    23.615385
Name: age, dtype: float64, 15    24.555556
Name: age, dtype: float64, 14    24.888889
Name: age, dtype: float64, 18    24.535714
Name: age, dtype: float64], [12    22.0
Name: age, dtype: float64, 11    23.184211
Name: age, dtype: float64, 5    23.885246
Name: age, dtype: float64, 16    22.375
Name: age, dtype: float64, 1    25.206897
Name: age, dtype: float64, 13    24.052632
Name: age, dtype: float64, 19    24.024691
Name: age, dtype: float64, 7    25.119048
Name: age, dtype: float64, 10    24.911765
Name: age, dtype: float64, 18    24.6875
Name: age, dtype: float64, 17    23.830189
Name: age, dtype: float64, 6    26.333333
Name: age, dtype: float64, 14    25.0
Name: age, dtype: float64, 0    25.866667
Name: age, dtype: float64, 3    27.473684
Name: age, dtype: float64, 15    25.117647
Name: age, dtype: float64, 2    24.666667
Name: age, dtype: float64, 4    26.114286
Name: age, dtype: float64, 8    25.068966
Name: age, dtype: float64, 9    25.125
Name: age, dtype: float64], [9    23.827586
Name: age, dtype: float64, 10    22.914894
Name: age, dtype: float64, 11    24.875
Name: age, dtype: float64, 5    25.55102
Name: age, dtype: float64, 8    25.72
Name: age, dtype: float64, 16    23.807692
Name: age, dtype: float64, 19    23.306122
Name: age, dtype: float64, 1    24.916667
Name: age, dtype: float64, 14    26.295455
Name: age, dtype: float64, 4    27.578947
Name: age, dtype: float64, 15    25.433333
Name: age, dtype: float64, 7    25.522727
Name: age, dtype: float64, 12    24.88
Name: age, dtype: float64, 6    26.214286
Name: age, dtype: float64, 3    24.357143
Name: age, dtype: float64, 18    26.555556
Name: age, dtype: float64, 2    26.52
Name: age, dtype: float64, 0    24.576923
Name: age, dtype: float64, 17    22.97561
Name: age, dtype: float64, 13    23.862745
Name: age, dtype: float64], [11    22.64
Name: age, dtype: float64, 12    25.24
Name: age, dtype: float64, 10    24.034483
Name: age, dtype: float64, 4    25.333333
Name: age, dtype: float64, 9    25.9
Name: age, dtype: float64, 18    27.28125
Name: age, dtype: float64, 16    24.538462
Name: age, dtype: float64, 0    25.46875
Name: age, dtype: float64, 8    23.322581
Name: age, dtype: float64, 6    26.15
Name: age, dtype: float64, 1    26.655172
Name: age, dtype: float64, 13    25.5
Name: age, dtype: float64, 19    23.625
Name: age, dtype: float64, 5    24.45
Name: age, dtype: float64, 15    25.707317
Name: age, dtype: float64, 2    24.823529
Name: age, dtype: float64, 3    26.0
Name: age, dtype: float64, 7    26.046512
Name: age, dtype: float64, 17    25.952381
Name: age, dtype: float64, 14    24.6
Name: age, dtype: float64]]

In [146]:
serieA = pd.read_csv('data/concat_years/serieA.csv')

serieA2004 = pd.read_csv('data/AverageAge/2004/Avg_serieA2004Age.csv')
serieA2005 = pd.read_csv('data/AverageAge/2005/Avg_serieA2005Age.csv')
serieA2006 = pd.read_csv('data/AverageAge/2006/Avg_serieA2006Age.csv')
serieA2007 = pd.read_csv('data/AverageAge/2007/Avg_serieA2007Age.csv')
serieA2008 = pd.read_csv('data/AverageAge/2008/Avg_serieA2008Age.csv')
serieA2009 = pd.read_csv('data/AverageAge/2009/Avg_serieA2009Age.csv')
serieA2010 = pd.read_csv('data/AverageAge/2010/Avg_serieA2010Age.csv')
serieA2011 = pd.read_csv('data/AverageAge/2011/Avg_serieA2011Age.csv')
serieA2012 = pd.read_csv('data/AverageAge/2012/Avg_serieA2012Age.csv')
serieA2013 = pd.read_csv('data/AverageAge/2013/Avg_serieA2013Age.csv')
serieA2014 = pd.read_csv('data/AverageAge/2014/Avg_serieA2014Age.csv')
serieA2015 = pd.read_csv('data/AverageAge/2015/Avg_serieA2015Age.csv')
serieA2016 = pd.read_csv('data/AverageAge/2016/Avg_serieA2016Age.csv')
serieA2017 = pd.read_csv('data/AverageAge/2017/Avg_serieA2017Age.csv')
serieA2018 = pd.read_csv('data/AverageAge/2018/Avg_serieA2018Age.csv')
serieA2019 = pd.read_csv('data/AverageAge/2019/Avg_serieA2019Age.csv')
serieA2020 = pd.read_csv('data/AverageAge/2020/Avg_serieA2020Age.csv')

list_clubsserieA2004 = serieA2004['club_name'].to_list()
list_clubsserieA2005 = serieA2005['club_name'].to_list()
list_clubsserieA2006 = serieA2006['club_name'].to_list()
list_clubsserieA2007 = serieA2007['club_name'].to_list()
list_clubsserieA2008 = serieA2008['club_name'].to_list()
list_clubsserieA2009 = serieA2009['club_name'].to_list()
list_clubsserieA2010 = serieA2010['club_name'].to_list()
list_clubsserieA2011 = serieA2011['club_name'].to_list()
list_clubsserieA2012 = serieA2012['club_name'].to_list()
list_clubsserieA2013 = serieA2013['club_name'].to_list()
list_clubsserieA2014 = serieA2014['club_name'].to_list()
list_clubsserieA2015 = serieA2015['club_name'].to_list()
list_clubsserieA2016 = serieA2016['club_name'].to_list()
list_clubsserieA2017 = serieA2017['club_name'].to_list()
list_clubsserieA2018 = serieA2018['club_name'].to_list()
list_clubsserieA2019 = serieA2019['club_name'].to_list()
list_clubsserieA2020 = serieA2020['club_name'].to_list()

list_age_serieA = []

list_age_serieA.append(age_league(serieA, serieA2004, list_clubsserieA2004, 0))
list_age_serieA.append(age_league(serieA, serieA2005, list_clubsserieA2005, 20))
list_age_serieA.append(age_league(serieA, serieA2006, list_clubsserieA2006, 40))
list_age_serieA.append(age_league(serieA, serieA2007, list_clubsserieA2007, 60))
list_age_serieA.append(age_league(serieA, serieA2008, list_clubsserieA2008, 80))
list_age_serieA.append(age_league(serieA, serieA2009, list_clubsserieA2009, 100))
list_age_serieA.append(age_league(serieA, serieA2010, list_clubsserieA2010, 120))
list_age_serieA.append(age_league(serieA, serieA2011, list_clubsserieA2011, 140))
list_age_serieA.append(age_league(serieA, serieA2012, list_clubsserieA2012, 160))
list_age_serieA.append(age_league(serieA, serieA2013, list_clubsserieA2013, 180))
list_age_serieA.append(age_league(serieA, serieA2014, list_clubsserieA2014, 200))
list_age_serieA.append(age_league(serieA, serieA2015, list_clubsserieA2015, 220))
list_age_serieA.append(age_league(serieA, serieA2016, list_clubsserieA2016, 240))
list_age_serieA.append(age_league(serieA, serieA2017, list_clubsserieA2017, 260))
list_age_serieA.append(age_league(serieA, serieA2018, list_clubsserieA2018, 280))
list_age_serieA.append(age_league(serieA, serieA2019, list_clubsserieA2019, 300))
list_age_serieA.append(age_league(serieA, serieA2020, list_clubsserieA2020, 320))

print(list_age_serieA)

#list => faire de list_age_serieA pas une liste de liste, mais une seule liste avec une fonction...
#serieA['Age'] = list
#serieA.to_csv('data/concat_years_age/serieA.csv', index=False)

[[12    23.4
Name: age, dtype: float64, 0    23.551724
Name: age, dtype: float64, 19    24.62069
Name: age, dtype: float64, 16    24.947368
Name: age, dtype: float64, 18    24.45
Name: age, dtype: float64, 11    24.810811
Name: age, dtype: float64, 4    22.5
Name: age, dtype: float64, 3    24.090909
Name: age, dtype: float64, 14    25.285714
Name: age, dtype: float64, 17    23.3
Name: age, dtype: float64, 8    24.409091
Name: age, dtype: float64, 15    26.823529
Name: age, dtype: float64, 1    26.285714
Name: age, dtype: float64, 9    23.903846
Name: age, dtype: float64, 2    25.128205
Name: age, dtype: float64, 13    24.693878
Name: age, dtype: float64, 7    23.742857
Name: age, dtype: float64, 5    23.529412
Name: age, dtype: float64], [4    23.117647
Name: age, dtype: float64, 0    24.888889
Name: age, dtype: float64, 7    23.897436
Name: age, dtype: float64, 18    24.055556
Name: age, dtype: float64, 3    25.914286
Name: age, dtype: float64, 12    23.736842
Name: age, dtype: float64, 8    24.266667
Name: age, dtype: float64, 2    26.272727
Name: age, dtype: float64, 5    25.230769
Name: age, dtype: float64, 19    23.459016
Name: age, dtype: float64, 16    24.194444
Name: age, dtype: float64, 13    24.245283
Name: age, dtype: float64, 6    26.454545
Name: age, dtype: float64, 1    25.977273
Name: age, dtype: float64, 14    26.025641
Name: age, dtype: float64, 10    23.878049
Name: age, dtype: float64, 17    22.484848
Name: age, dtype: float64, 11    23.85
Name: age, dtype: float64], [4    24.888889
Name: age, dtype: float64, 15    23.918919
Name: age, dtype: float64, 0    24.472222
Name: age, dtype: float64, 18    24.906977
Name: age, dtype: float64, 2    26.09375
Name: age, dtype: float64, 10    23.206897
Name: age, dtype: float64, 6    24.030303
Name: age, dtype: float64, 17    25.22449
Name: age, dtype: float64, 19    22.698113
Name: age, dtype: float64, 3    26.473684
Name: age, dtype: float64, 13    24.451613
Name: age, dtype: float64, 8    25.361111
Name: age, dtype: float64, 14    24.714286
Name: age, dtype: float64, 1    24.787234
Name: age, dtype: float64, 16    26.909091
Name: age, dtype: float64, 7    24.5
Name: age, dtype: float64, 9    24.947368
Name: age, dtype: float64, 5    25.890625
Name: age, dtype: float64, 12    26.46
Name: age, dtype: float64], [4    23.421053
Name: age, dtype: float64, 11    23.62069
Name: age, dtype: float64, 2    22.0
Name: age, dtype: float64, 0    24.034483
Name: age, dtype: float64, 17    23.891304
Name: age, dtype: float64, 19    22.470588
Name: age, dtype: float64, 15    23.9375
Name: age, dtype: float64, 5    24.958333
Name: age, dtype: float64, 10    24.294118
Name: age, dtype: float64, 18    24.147059
Name: age, dtype: float64, 14    24.709677
Name: age, dtype: float64, 1    24.054545
Name: age, dtype: float64, 6    24.826087
Name: age, dtype: float64, 16    27.853659
Name: age, dtype: float64, 13    23.48
Name: age, dtype: float64, 7    25.4
Name: age, dtype: float64, 8    22.904762
Name: age, dtype: float64, 12    24.326531
Name: age, dtype: float64, 3    27.382353
Name: age, dtype: float64], [11    22.612245
Name: age, dtype: float64, 0    25.076923
Name: age, dtype: float64, 2    23.486486
Name: age, dtype: float64, 10    23.013699
Name: age, dtype: float64, 3    21.696429
Name: age, dtype: float64, 19    22.932432
Name: age, dtype: float64, 18    23.25
Name: age, dtype: float64, 6    23.482759
Name: age, dtype: float64, 13    24.794872
Name: age, dtype: float64, 4    23.520833
Name: age, dtype: float64, 14    25.896552
Name: age, dtype: float64, 16    22.389831
Name: age, dtype: float64, 1    23.7
Name: age, dtype: float64, 7    24.552632
Name: age, dtype: float64, 8    24.54
Name: age, dtype: float64, 15    26.363636
Name: age, dtype: float64, 12    23.77551
Name: age, dtype: float64, 17    23.186047
Name: age, dtype: float64], [5    23.651163
Name: age, dtype: float64, 0    24.588235
Name: age, dtype: float64, 17    23.846154
Name: age, dtype: float64, 18    23.08
Name: age, dtype: float64, 16    25.40625
Name: age, dtype: float64, 13    23.325
Name: age, dtype: float64, 14    24.027027
Name: age, dtype: float64, 12    22.977778
Name: age, dtype: float64, 3    24.264706
Name: age, dtype: float64, 2    23.291667
Name: age, dtype: float64, 15    23.820513
Name: age, dtype: float64, 9    25.241379
Name: age, dtype: float64, 10    24.491525
Name: age, dtype: float64, 19    22.644737
Name: age, dtype: float64, 8    23.04
Name: age, dtype: float64, 6    23.612245
Name: age, dtype: float64, 1    23.907692
Name: age, dtype: float64, 4    24.844444
Name: age, dtype: float64], [1    24.305085
Name: age, dtype: float64, 15    25.027027
Name: age, dtype: float64, 19    22.662162
Name: age, dtype: float64, 14    26.413793
Name: age, dtype: float64, 4    25.230769
Name: age, dtype: float64, 12    24.333333
Name: age, dtype: float64, 18    23.583333
Name: age, dtype: float64, 2    22.606061
Name: age, dtype: float64, 11    22.6
Name: age, dtype: float64, 9    24.139241
Name: age, dtype: float64, 13    23.349398
Name: age, dtype: float64, 8    23.7
Name: age, dtype: float64, 7    25.516129
Name: age, dtype: float64, 0    24.473684
Name: age, dtype: float64, 17    24.510204
Name: age, dtype: float64, 16    24.06
Name: age, dtype: float64, 6    24.405405
Name: age, dtype: float64, 3    24.131148
Name: age, dtype: float64], [12    24.2
Name: age, dtype: float64, 1    23.365079
Name: age, dtype: float64, 19    23.486842
Name: age, dtype: float64, 15    25.153846
Name: age, dtype: float64, 16    25.172414
Name: age, dtype: float64, 4    23.5
Name: age, dtype: float64, 14    23.176471
Name: age, dtype: float64, 9    23.743902
Name: age, dtype: float64, 8    25.0
Name: age, dtype: float64, 5    25.413043
Name: age, dtype: float64, 3    23.759259
Name: age, dtype: float64, 2    24.175676
Name: age, dtype: float64, 7    23.676471
Name: age, dtype: float64, 18    24.333333
Name: age, dtype: float64, 11    23.424242
Name: age, dtype: float64, 17    25.413043
Name: age, dtype: float64, 13    25.553191
Name: age, dtype: float64, 0    24.329114
Name: age, dtype: float64], [12    23.65625
Name: age, dtype: float64, 15    24.146341
Name: age, dtype: float64, 0    24.732394
Name: age, dtype: float64, 2    25.444444
Name: age, dtype: float64, 19    24.013333
Name: age, dtype: float64, 3    23.046154
Name: age, dtype: float64, 14    24.846154
Name: age, dtype: float64, 7    23.44898
Name: age, dtype: float64, 13    22.949367
Name: age, dtype: float64, 6    24.028571
Name: age, dtype: float64, 8    24.706667
Name: age, dtype: float64, 17    24.203125
Name: age, dtype: float64, 4    25.78
Name: age, dtype: float64, 16    25.90566
Name: age, dtype: float64, 11    24.490566
Name: age, dtype: float64, 18    24.796875
Name: age, dtype: float64, 1    25.03125
Name: age, dtype: float64, 9    23.924242
Name: age, dtype: float64], [12    22.967213
Name: age, dtype: float64, 3    23.166667
Name: age, dtype: float64, 15    26.054545
Name: age, dtype: float64, 1    24.8125
Name: age, dtype: float64, 13    22.647564
Name: age, dtype: float64, 16    25.042553
Name: age, dtype: float64, 0    23.5
Name: age, dtype: float64, 14    24.394737
Name: age, dtype: float64, 11    24.618421
Name: age, dtype: float64, 4    24.169811
Name: age, dtype: float64, 17    23.128571
Name: age, dtype: float64, 19    22.974359
Name: age, dtype: float64, 10    25.010417
Name: age, dtype: float64, 6    22.655172
Name: age, dtype: float64, 8    23.849462
Name: age, dtype: float64, 18    24.305085
Name: age, dtype: float64, 7    23.844828
Name: age, dtype: float64, 2    23.722222
Name: age, dtype: float64], [11    22.356322
Name: age, dtype: float64, 3    23.015385
Name: age, dtype: float64, 13    22.977778
Name: age, dtype: float64, 2    23.886792
Name: age, dtype: float64, 14    24.851064
Name: age, dtype: float64, 8    24.761364
Name: age, dtype: float64, 16    23.756757
Name: age, dtype: float64, 10    23.384615
Name: age, dtype: float64, 15    24.677419
Name: age, dtype: float64, 1    24.253165
Name: age, dtype: float64, 17    23.457627
Name: age, dtype: float64, 18    24.568182
Name: age, dtype: float64, 9    24.465909
Name: age, dtype: float64, 6    24.179245
Name: age, dtype: float64, 7    22.982759
Name: age, dtype: float64, 19    23.443038
Name: age, dtype: float64, 4    23.57971
Name: age, dtype: float64, 5    23.0
Name: age, dtype: float64, 0    24.390244
Name: age, dtype: float64, 12    23.678431
Name: age, dtype: float64], [12    22.280374
Name: age, dtype: float64, 14    24.12
Name: age, dtype: float64, 2    22.804598
Name: age, dtype: float64, 11    23.206522
Name: age, dtype: float64, 1    24.871429
Name: age, dtype: float64, 18    23.794872
Name: age, dtype: float64, 0    24.041667
Name: age, dtype: float64, 13    23.903846
Name: age, dtype: float64, 6    23.835165
Name: age, dtype: float64, 7    22.897959
Name: age, dtype: float64, 9    24.534247
Name: age, dtype: float64, 15    23.163636
Name: age, dtype: float64, 3    23.989247
Name: age, dtype: float64, 16    24.318182
Name: age, dtype: float64, 17    23.046875
Name: age, dtype: float64, 19    23.512821
Name: age, dtype: float64, 8    24.162162
Name: age, dtype: float64, 10    25.103896
Name: age, dtype: float64], [12    23.053191
Name: age, dtype: float64, 2    23.683544
Name: age, dtype: float64, 14    22.978723
Name: age, dtype: float64, 3    24.126437
Name: age, dtype: float64, 13    24.045455
Name: age, dtype: float64, 0    25.365854
Name: age, dtype: float64, 11    22.84
Name: age, dtype: float64, 1    23.566667
Name: age, dtype: float64, 15    23.867647
Name: age, dtype: float64, 16    24.486842
Name: age, dtype: float64, 5    23.803922
Name: age, dtype: float64, 18    23.5
Name: age, dtype: float64, 19    23.723684
Name: age, dtype: float64, 6    23.875
Name: age, dtype: float64, 10    23.714286
Name: age, dtype: float64, 9    23.538462
Name: age, dtype: float64, 8    22.977778
Name: age, dtype: float64, 17    23.490909
Name: age, dtype: float64, 7    23.514851
Name: age, dtype: float64], [12    22.940476
Name: age, dtype: float64, 15    23.761905
Name: age, dtype: float64, 2    23.821918
Name: age, dtype: float64, 11    23.141026
Name: age, dtype: float64, 14    23.085714
Name: age, dtype: float64, 0    24.468085
Name: age, dtype: float64, 3    23.27551
Name: age, dtype: float64, 1    23.876923
Name: age, dtype: float64, 16    23.442308
Name: age, dtype: float64, 17    23.272727
Name: age, dtype: float64, 18    22.744681
Name: age, dtype: float64, 9    23.653846
Name: age, dtype: float64, 7    23.779221
Name: age, dtype: float64, 19    24.115385
Name: age, dtype: float64, 6    24.9375
Name: age, dtype: float64, 8    23.673077
Name: age, dtype: float64, 10    24.872727
Name: age, dtype: float64, 4    25.061538
Name: age, dtype: float64], [11    25.590909
Name: age, dtype: float64, 15    24.522727
Name: age, dtype: float64, 3    22.578947
Name: age, dtype: float64, 10    22.469697
Name: age, dtype: float64, 0    25.45
Name: age, dtype: float64, 2    23.606557
Name: age, dtype: float64, 16    23.15873
Name: age, dtype: float64, 14    24.95122
Name: age, dtype: float64, 17    23.936508
Name: age, dtype: float64, 18    22.947368
Name: age, dtype: float64, 19    24.754098
Name: age, dtype: float64, 13    24.46875
Name: age, dtype: float64, 5    25.06383
Name: age, dtype: float64, 1    23.380952
Name: age, dtype: float64, 9    24.114286
Name: age, dtype: float64, 7    23.134328
Name: age, dtype: float64, 8    25.857143
Name: age, dtype: float64, 6    24.84507
Name: age, dtype: float64], [10    24.647059
Name: age, dtype: float64, 9    23.121212
Name: age, dtype: float64, 3    22.935484
Name: age, dtype: float64, 13    22.886792
Name: age, dtype: float64, 2    23.660377
Name: age, dtype: float64, 0    24.871795
Name: age, dtype: float64, 14    23.935484
Name: age, dtype: float64, 18    22.746479
Name: age, dtype: float64, 8    24.577778
Name: age, dtype: float64, 1    23.791045
Name: age, dtype: float64, 19    25.603774
Name: age, dtype: float64, 6    24.88
Name: age, dtype: float64, 16    24.21875
Name: age, dtype: float64, 15    23.403846
Name: age, dtype: float64, 7    23.560748
Name: age, dtype: float64, 17    25.37931
Name: age, dtype: float64, 5    25.216216
Name: age, dtype: float64, 12    24.913793
Name: age, dtype: float64], [10    24.294118
Name: age, dtype: float64, 0    24.585366
Name: age, dtype: float64, 3    22.464789
Name: age, dtype: float64, 11    24.193548
Name: age, dtype: float64, 14    24.55814
Name: age, dtype: float64, 13    25.459459
Name: age, dtype: float64, 2    25.232558
Name: age, dtype: float64, 18    22.862745
Name: age, dtype: float64, 17    23.903846
Name: age, dtype: float64, 9    24.917808
Name: age, dtype: float64, 8    23.505618
Name: age, dtype: float64, 1    24.614035
Name: age, dtype: float64, 19    24.465116
Name: age, dtype: float64, 15    24.458333
Name: age, dtype: float64, 6    26.06383
Name: age, dtype: float64, 16    23.820513
Name: age, dtype: float64, 4    25.794118
Name: age, dtype: float64, 7    24.607843
Name: age, dtype: float64]]

In [152]:
ligue1 = pd.read_csv('data/concat_years/ligue1.csv')

ligue12004 = pd.read_csv('data/AverageAge/2004/Avg_ligue1_2004Age.csv')
ligue12005 = pd.read_csv('data/AverageAge/2005/Avg_ligue1_2005Age.csv')
ligue12006 = pd.read_csv('data/AverageAge/2006/Avg_ligue1_2006Age.csv')
ligue12007 = pd.read_csv('data/AverageAge/2007/Avg_ligue1_2007Age.csv')
ligue12008 = pd.read_csv('data/AverageAge/2008/Avg_ligue1_2008Age.csv')
ligue12009 = pd.read_csv('data/AverageAge/2009/Avg_ligue1_2009Age.csv')
ligue12010 = pd.read_csv('data/AverageAge/2010/Avg_ligue1_2010Age.csv')
ligue12011 = pd.read_csv('data/AverageAge/2011/Avg_ligue1_2011Age.csv')
ligue12012 = pd.read_csv('data/AverageAge/2012/Avg_ligue1_2012Age.csv')
ligue12013 = pd.read_csv('data/AverageAge/2013/Avg_ligue1_2013Age.csv')
ligue12014 = pd.read_csv('data/AverageAge/2014/Avg_ligue1_2014Age.csv')
ligue12015 = pd.read_csv('data/AverageAge/2015/Avg_ligue1_2015Age.csv')
ligue12016 = pd.read_csv('data/AverageAge/2016/Avg_ligue1_2016Age.csv')
ligue12017 = pd.read_csv('data/AverageAge/2017/Avg_ligue1_2017Age.csv')
ligue12018 = pd.read_csv('data/AverageAge/2018/Avg_ligue1_2018Age.csv')
ligue12019 = pd.read_csv('data/AverageAge/2019/Avg_ligue1_2019Age.csv')
ligue12020 = pd.read_csv('data/AverageAge/2020/Avg_ligue1_2020Age.csv')

list_clubsligue12004 = ligue12004['club_name'].to_list()
list_clubsligue12005 = ligue12005['club_name'].to_list()
list_clubsligue12006 = ligue12006['club_name'].to_list()
list_clubsligue12007 = ligue12007['club_name'].to_list()
list_clubsligue12008 = ligue12008['club_name'].to_list()
list_clubsligue12009 = ligue12009['club_name'].to_list()
list_clubsligue12010 = ligue12010['club_name'].to_list()
list_clubsligue12011 = ligue12011['club_name'].to_list()
list_clubsligue12012 = ligue12012['club_name'].to_list()
list_clubsligue12013 = ligue12013['club_name'].to_list()
list_clubsligue12014 = ligue12014['club_name'].to_list()
list_clubsligue12015 = ligue12015['club_name'].to_list()
list_clubsligue12016 = ligue12016['club_name'].to_list()
list_clubsligue12017 = ligue12017['club_name'].to_list()
list_clubsligue12018 = ligue12018['club_name'].to_list()
list_clubsligue12019 = ligue12019['club_name'].to_list()
list_clubsligue12020 = ligue12020['club_name'].to_list()

list_age_ligue1 = []

list_age_ligue1.append(age_league(ligue1, ligue12004, list_clubsligue12004, 0))
list_age_ligue1.append(age_league(ligue1, ligue12005, list_clubsligue12005, 20))
list_age_ligue1.append(age_league(ligue1, ligue12006, list_clubsligue12006, 40))
list_age_ligue1.append(age_league(ligue1, ligue12007, list_clubsligue12007, 60))
list_age_ligue1.append(age_league(ligue1, ligue12008, list_clubsligue12008, 80))
list_age_ligue1.append(age_league(ligue1, ligue12009, list_clubsligue12009, 100))
list_age_ligue1.append(age_league(ligue1, ligue12010, list_clubsligue12010, 120))
list_age_ligue1.append(age_league(ligue1, ligue12011, list_clubsligue12011, 140))
list_age_ligue1.append(age_league(ligue1, ligue12012, list_clubsligue12012, 160))
list_age_ligue1.append(age_league(ligue1, ligue12013, list_clubsligue12013, 180))
list_age_ligue1.append(age_league(ligue1, ligue12014, list_clubsligue12014, 200))
list_age_ligue1.append(age_league(ligue1, ligue12015, list_clubsligue12015, 220))
list_age_ligue1.append(age_league(ligue1, ligue12016, list_clubsligue12016, 240))
list_age_ligue1.append(age_league(ligue1, ligue12017, list_clubsligue12017, 260))
list_age_ligue1.append(age_league(ligue1, ligue12018, list_clubsligue12018, 280))
list_age_ligue1.append(age_league(ligue1, ligue12019, list_clubsligue12019, 300))
list_age_ligue1.append(age_league(ligue1, ligue12020, list_clubsligue12020, 320))

print(list_age_ligue1)

#list => faire de list_age_ligue1 pas une liste de liste, mais une seule liste avec une fonction...
#ligue1['Age'] = list
#ligue1.to_csv('data/concat_years_age/ligue1.csv', index=False)

[[12    24.032258
Name: age, dtype: float64, 10    24.410256
Name: age, dtype: float64, 2    23.780488
Name: age, dtype: float64, 19    24.354839
Name: age, dtype: float64, 13    25.169811
Name: age, dtype: float64, 3    23.515152
Name: age, dtype: float64, 15    25.026316
Name: age, dtype: float64, 1    22.791667
Name: age, dtype: float64, 14    24.85
Name: age, dtype: float64, 8    24.0
Name: age, dtype: float64, 16    23.724138
Name: age, dtype: float64, 11    25.295455
Name: age, dtype: float64, 9    23.137931
Name: age, dtype: float64, 0    27.142857
Name: age, dtype: float64, 4    23.53125
Name: age, dtype: float64, 6    23.021739
Name: age, dtype: float64, 7    23.181818
Name: age, dtype: float64, 18    24.642857
Name: age, dtype: float64, 17    26.451613
Name: age, dtype: float64, 5    25.365854
Name: age, dtype: float64], [14    22.066667
Name: age, dtype: float64, 6    23.69697
Name: age, dtype: float64, 11    22.588235
Name: age, dtype: float64, 17    23.75
Name: age, dtype: float64, 15    24.885246
Name: age, dtype: float64, 1    23.47619
Name: age, dtype: float64, 19    23.12
Name: age, dtype: float64, 13    24.685714
Name: age, dtype: float64, 16    24.689655
Name: age, dtype: float64, 2    23.785714
Name: age, dtype: float64, 12    23.783784
Name: age, dtype: float64, 3    24.846154
Name: age, dtype: float64, 4    23.645161
Name: age, dtype: float64, 8    23.818182
Name: age, dtype: float64, 9    22.914286
Name: age, dtype: float64, 10    24.315789
Name: age, dtype: float64, 5    24.233333
Name: age, dtype: float64, 0    25.516129
Name: age, dtype: float64, 18    23.527778
Name: age, dtype: float64, 7    23.346154
Name: age, dtype: float64], [14    23.296296
Name: age, dtype: float64, 15    25.115385
Name: age, dtype: float64, 10    25.315789
Name: age, dtype: float64, 18    23.235294
Name: age, dtype: float64, 17    22.90625
Name: age, dtype: float64, 6    23.576923
Name: age, dtype: float64, 9    22.421053
Name: age, dtype: float64, 0    24.862069
Name: age, dtype: float64, 1    24.581395
Name: age, dtype: float64, 11    22.4
Name: age, dtype: float64, 3    24.1875
Name: age, dtype: float64, 12    22.652174
Name: age, dtype: float64, 2    22.941176
Name: age, dtype: float64, 7    23.789474
Name: age, dtype: float64, 16    24.848485
Name: age, dtype: float64, 13    25.103448
Name: age, dtype: float64, 19    25.6
Name: age, dtype: float64, 5    26.470588
Name: age, dtype: float64, 4    26.466667
Name: age, dtype: float64, 8    24.673913
Name: age, dtype: float64], [12    24.212121
Name: age, dtype: float64, 4    22.969697
Name: age, dtype: float64, 13    23.773585
Name: age, dtype: float64, 2    23.3125
Name: age, dtype: float64, 3    24.333333
Name: age, dtype: float64, 18    25.457143
Name: age, dtype: float64, 9    23.297297
Name: age, dtype: float64, 11    24.571429
Name: age, dtype: float64, 10    23.111111
Name: age, dtype: float64, 5    23.75
Name: age, dtype: float64, 17    24.833333
Name: age, dtype: float64, 1    23.487805
Name: age, dtype: float64, 19    27.842105
Name: age, dtype: float64, 7    23.513514
Name: age, dtype: float64, 0    24.40625
Name: age, dtype: float64, 14    23.1
Name: age, dtype: float64, 8    22.137931
Name: age, dtype: float64, 15    24.756098
Name: age, dtype: float64, 16    23.642857
Name: age, dtype: float64, 6    23.314286
Name: age, dtype: float64], [5    21.884615
Name: age, dtype: float64, 15    24.28
Name: age, dtype: float64, 14    25.068966
Name: age, dtype: float64, 9    25.078947
Name: age, dtype: float64, 11    23.166667
Name: age, dtype: float64, 16    24.451613
Name: age, dtype: float64, 18    23.166667
Name: age, dtype: float64, 1    23.333333
Name: age, dtype: float64, 13    24.25
Name: age, dtype: float64, 6    23.517241
Name: age, dtype: float64, 2    22.934783
Name: age, dtype: float64, 19    26.0
Name: age, dtype: float64, 10    24.608696
Name: age, dtype: float64, 8    23.888889
Name: age, dtype: float64, 3    24.241379
Name: age, dtype: float64, 12    22.857143
Name: age, dtype: float64, 4    23.806452
Name: age, dtype: float64, 17    23.375
Name: age, dtype: float64, 7    25.157895
Name: age, dtype: float64, 0    23.783784
Name: age, dtype: float64], [14    24.395833
Name: age, dtype: float64, 13    22.538462
Name: age, dtype: float64, 0    22.814815
Name: age, dtype: float64, 9    24.225806
Name: age, dtype: float64, 11    25.055556
Name: age, dtype: float64, 4    21.655172
Name: age, dtype: float64, 5    25.277778
Name: age, dtype: float64, 1    24.384615
Name: age, dtype: float64, 17    22.820513
Name: age, dtype: float64, 19    26.863636
Name: age, dtype: float64, 16    22.884615
Name: age, dtype: float64, 2    23.785714
Name: age, dtype: float64, 15    25.78125
Name: age, dtype: float64, 7    25.043478
Name: age, dtype: float64, 12    26.391304
Name: age, dtype: float64, 6    24.970588
Name: age, dtype: float64, 3    24.576923
Name: age, dtype: float64, 10    22.9
Name: age, dtype: float64, 18    24.733333
Name: age, dtype: float64, 8    26.482759
Name: age, dtype: float64], [9    24.5625
Name: age, dtype: float64, 13    24.121212
Name: age, dtype: float64, 12    24.777778
Name: age, dtype: float64, 14    24.818182
Name: age, dtype: float64, 7    24.3
Name: age, dtype: float64, 18    23.162162
Name: age, dtype: float64, 5    23.166667
Name: age, dtype: float64, 8    22.85
Name: age, dtype: float64, 0    23.521739
Name: age, dtype: float64, 3    25.0
Name: age, dtype: float64, 6    23.428571
Name: age, dtype: float64, 19    25.047619
Name: age, dtype: float64, 2    24.354839
Name: age, dtype: float64, 10    24.2
Name: age, dtype: float64, 16    25.055556
Name: age, dtype: float64, 17    25.72
Name: age, dtype: float64, 11    24.115385
Name: age, dtype: float64, 1    24.410714
Name: age, dtype: float64, 15    23.695652
Name: age, dtype: float64, 4    25.877551
Name: age, dtype: float64], [11    24.619048
Name: age, dtype: float64, 15    26.090909
Name: age, dtype: float64, 10    25.108108
Name: age, dtype: float64, 13    22.238095
Name: age, dtype: float64, 5    23.774194
Name: age, dtype: float64, 18    24.086957
Name: age, dtype: float64, 3    25.47619
Name: age, dtype: float64, 8    23.608696
Name: age, dtype: float64, 9    25.866667
Name: age, dtype: float64, 14    25.65625
Name: age, dtype: float64, 2    25.314286
Name: age, dtype: float64, 19    24.75
Name: age, dtype: float64, 12    25.666667
Name: age, dtype: float64, 7    23.84
Name: age, dtype: float64, 17    25.730769
Name: age, dtype: float64, 0    25.190476
Name: age, dtype: float64, 6    24.571429
Name: age, dtype: float64, 16    22.875
Name: age, dtype: float64, 4    24.026316
Name: age, dtype: float64, 1    23.2
Name: age, dtype: float64], [14    25.538462
Name: age, dtype: float64, 13    24.517241
Name: age, dtype: float64, 12    23.0
Name: age, dtype: float64, 11    23.305556
Name: age, dtype: float64, 2    26.205882
Name: age, dtype: float64, 9    23.3
Name: age, dtype: float64, 4    22.777778
Name: age, dtype: float64, 5    24.038462
Name: age, dtype: float64, 10    23.529412
Name: age, dtype: float64, 7    24.428571
Name: age, dtype: float64, 19    23.631579
Name: age, dtype: float64, 15    25.481481
Name: age, dtype: float64, 17    25.0
Name: age, dtype: float64, 17    25.0
Name: age, dtype: float64, 6    25.083333
Name: age, dtype: float64, 8    26.5
Name: age, dtype: float64, 0    26.08
Name: age, dtype: float64, 1    24.361702
Name: age, dtype: float64, 3    24.25
Name: age, dtype: float64, 16    27.0
Name: age, dtype: float64], [15    24.314286
Name: age, dtype: float64, 1    23.465517
Name: age, dtype: float64, 10    23.0
Name: age, dtype: float64, 2    23.085714
Name: age, dtype: float64, 13    23.590909
Name: age, dtype: float64, 14    22.964286
Name: age, dtype: float64, 4    25.045455
Name: age, dtype: float64, 5    22.678571
Name: age, dtype: float64, 8    24.269231
Name: age, dtype: float64, 16    26.027027
Name: age, dtype: float64, 17    23.684211
Name: age, dtype: float64, 17    23.684211
Name: age, dtype: float64, 6    26.35
Name: age, dtype: float64, 9    24.470588
Name: age, dtype: float64, 11    24.56
Name: age, dtype: float64, 3    24.857143
Name: age, dtype: float64, 12    23.2
Name: age, dtype: float64, 7    24.033333
Name: age, dtype: float64, 19    24.863636
Name: age, dtype: float64, 0    26.25641
Name: age, dtype: float64], [14    22.764706
Name: age, dtype: float64, 12    24.0625
Name: age, dtype: float64, 0    23.37037
Name: age, dtype: float64, 13    24.5625
Name: age, dtype: float64, 1    25.05
Name: age, dtype: float64, 3    23.939394
Name: age, dtype: float64, 10    23.48
Name: age, dtype: float64, 9    22.583333
Name: age, dtype: float64, 18    24.809524
Name: age, dtype: float64, 2    27.0
Name: age, dtype: float64, 11    24.923077
Name: age, dtype: float64, 16    24.270833
Name: age, dtype: float64, 17    25.96
Name: age, dtype: float64, 6    24.25
Name: age, dtype: float64, 18    24.809524
Name: age, dtype: float64, 4    23.657895
Name: age, dtype: float64, 7    23.95
Name: age, dtype: float64, 8    25.818182
Name: age, dtype: float64, 5    23.289474
Name: age, dtype: float64, 15    22.823529
Name: age, dtype: float64], [14    23.45
Name: age, dtype: float64, 12    23.625
Name: age, dtype: float64, 0    22.389831
Name: age, dtype: float64, 11    22.738095
Name: age, dtype: float64, 9    22.926829
Name: age, dtype: float64, 1    23.566667
Name: age, dtype: float64, 17    24.621622
Name: age, dtype: float64, 18    24.26087
Name: age, dtype: float64, 16    26.333333
Name: age, dtype: float64, 15    23.433333
Name: age, dtype: float64, 4    22.538462
Name: age, dtype: float64, 10    23.894737
Name: age, dtype: float64, 13    24.341463
Name: age, dtype: float64, 6    24.785714
Name: age, dtype: float64, 5    24.103448
Name: age, dtype: float64, 2    24.357143
Name: age, dtype: float64, 7    23.521739
Name: age, dtype: float64, 18    24.26087
Name: age, dtype: float64, 3    25.088235
Name: age, dtype: float64], [0    23.471698
Name: age, dtype: float64, 15    23.903226
Name: age, dtype: float64, 12    23.7
Name: age, dtype: float64, 13    23.038462
Name: age, dtype: float64, 14    24.843137
Name: age, dtype: float64, 5    24.535714
Name: age, dtype: float64, 8    24.64
Name: age, dtype: float64, 2    24.333333
Name: age, dtype: float64, 19    23.913043
Name: age, dtype: float64, 4    26.424242
Name: age, dtype: float64, 10    24.369565
Name: age, dtype: float64, 17    26.282051
Name: age, dtype: float64, 9    23.0
Name: age, dtype: float64, 7    24.415094
Name: age, dtype: float64, 11    23.9
Name: age, dtype: float64, 3    24.62069
Name: age, dtype: float64, 18    25.090909
Name: age, dtype: float64, 6    23.422222
Name: age, dtype: float64, 1    23.173913
Name: age, dtype: float64, 16    24.342857
Name: age, dtype: float64], [15    24.8
Name: age, dtype: float64, 0    22.959184
Name: age, dtype: float64, 13    22.45
Name: age, dtype: float64, 14    24.842105
Name: age, dtype: float64, 19    23.926829
Name: age, dtype: float64, 6    23.458333
Name: age, dtype: float64, 1    24.243902
Name: age, dtype: float64, 12    23.735294
Name: age, dtype: float64, 8    25.16
Name: age, dtype: float64, 11    24.366667
Name: age, dtype: float64, 3    24.44
Name: age, dtype: float64, 4    25.096774
Name: age, dtype: float64, 2    25.294118
Name: age, dtype: float64, 17    25.230769
Name: age, dtype: float64, 16    25.4
Name: age, dtype: float64, 18    24.15625
Name: age, dtype: float64, 10    23.213115
Name: age, dtype: float64, 9    25.384615
Name: age, dtype: float64, 5    26.25
Name: age, dtype: float64, 7    24.068182
Name: age, dtype: float64], [14    23.307692
Name: age, dtype: float64, 8    24.371429
Name: age, dtype: float64, 12    21.558824
Name: age, dtype: float64, 1    22.9
Name: age, dtype: float64, 13    24.347826
Name: age, dtype: float64, 9    24.26087
Name: age, dtype: float64, 11    22.52
Name: age, dtype: float64, 18    24.344828
Name: age, dtype: float64, 10    24.666667
Name: age, dtype: float64, 18    24.344828
Name: age, dtype: float64, 15    25.892857
Name: age, dtype: float64, 6    25.060606
Name: age, dtype: float64, 16    25.205128
Name: age, dtype: float64, 5    22.594595
Name: age, dtype: float64, 2    25.458333
Name: age, dtype: float64, 7    23.432432
Name: age, dtype: float64, 0    22.712121
Name: age, dtype: float64, 3    25.3
Name: age, dtype: float64, 17    24.862745
Name: age, dtype: float64, 4    25.84
Name: age, dtype: float64], [14    23.794872
Name: age, dtype: float64, 13    25.136364
Name: age, dtype: float64, 18    22.897436
Name: age, dtype: float64, 8    23.27027
Name: age, dtype: float64, 11    21.935484
Name: age, dtype: float64, 18    22.897436
Name: age, dtype: float64, 12    23.5
Name: age, dtype: float64, 9    23.939394
Name: age, dtype: float64, 0    23.111111
Name: age, dtype: float64, 15    25.285714
Name: age, dtype: float64, 16    25.911765
Name: age, dtype: float64, 4    24.432432
Name: age, dtype: float64, 6    24.333333
Name: age, dtype: float64, 17    24.576923
Name: age, dtype: float64, 5    23.342857
Name: age, dtype: float64, 3    23.580645
Name: age, dtype: float64, 1    22.976744
Name: age, dtype: float64, 10    24.970588
Name: age, dtype: float64, 2    24.065217
Name: age, dtype: float64, 7    24.146341
Name: age, dtype: float64], [7    23.666667
Name: age, dtype: float64, 13    23.419355
Name: age, dtype: float64, 0    23.546875
Name: age, dtype: float64, 11    24.2
Name: age, dtype: float64, 12    24.833333
Name: age, dtype: float64, 18    23.043478
Name: age, dtype: float64, 14    24.193548
Name: age, dtype: float64, 8    23.5
Name: age, dtype: float64, 10    21.6
Name: age, dtype: float64, 5    23.181818
Name: age, dtype: float64, 1    23.510638
Name: age, dtype: float64, 3    22.62963
Name: age, dtype: float64, 16    24.322581
Name: age, dtype: float64, 18    23.043478
Name: age, dtype: float64, 15    25.933333
Name: age, dtype: float64, 4    24.425
Name: age, dtype: float64, 17    24.096774
Name: age, dtype: float64, 6    24.375
Name: age, dtype: float64, 9    23.210526
Name: age, dtype: float64, 2    23.242424
Name: age, dtype: float64]]

In [161]:
bundesliga = pd.read_csv('data/concat_years/bundesliga.csv')

bundesliga2004 = pd.read_csv('data/AverageAge/2004/Avg_bundeshliga2004Age.csv')
bundesliga2005 = pd.read_csv('data/AverageAge/2005/Avg_bundeshliga2005Age.csv')
bundesliga2006 = pd.read_csv('data/AverageAge/2006/Avg_bundeshliga2006Age.csv')
bundesliga2007 = pd.read_csv('data/AverageAge/2007/Avg_bundeshliga2007Age.csv')
bundesliga2008 = pd.read_csv('data/AverageAge/2008/Avg_bundeshliga2008Age.csv')
bundesliga2009 = pd.read_csv('data/AverageAge/2009/Avg_bundeshliga2009Age.csv')
bundesliga2010 = pd.read_csv('data/AverageAge/2010/Avg_bundeshliga2010Age.csv')
bundesliga2011 = pd.read_csv('data/AverageAge/2011/Avg_bundeshliga2011Age.csv')
bundesliga2012 = pd.read_csv('data/AverageAge/2012/Avg_bundeshliga2012Age.csv')
bundesliga2013 = pd.read_csv('data/AverageAge/2013/Avg_bundeshliga2013Age.csv')
bundesliga2014 = pd.read_csv('data/AverageAge/2014/Avg_bundeshliga2014Age.csv')
bundesliga2015 = pd.read_csv('data/AverageAge/2015/Avg_bundeshliga2015Age.csv')
bundesliga2016 = pd.read_csv('data/AverageAge/2016/Avg_bundeshliga2016Age.csv')
bundesliga2017 = pd.read_csv('data/AverageAge/2017/Avg_bundeshliga2017Age.csv')
bundesliga2018 = pd.read_csv('data/AverageAge/2018/Avg_bundeshliga2018Age.csv')
bundesliga2019 = pd.read_csv('data/AverageAge/2019/Avg_bundeshliga2019Age.csv')
bundesliga2020 = pd.read_csv('data/AverageAge/2020/Avg_bundeshliga2020Age.csv')

list_clubsbundesliga2004 = bundesliga2004['club_name'].to_list()
list_clubsbundesliga2005 = bundesliga2005['club_name'].to_list()
list_clubsbundesliga2006 = bundesliga2006['club_name'].to_list()
list_clubsbundesliga2007 = bundesliga2007['club_name'].to_list()
list_clubsbundesliga2008 = bundesliga2008['club_name'].to_list()
list_clubsbundesliga2009 = bundesliga2009['club_name'].to_list()
list_clubsbundesliga2010 = bundesliga2010['club_name'].to_list()
list_clubsbundesliga2011 = bundesliga2011['club_name'].to_list()
list_clubsbundesliga2012 = bundesliga2012['club_name'].to_list()
list_clubsbundesliga2013 = bundesliga2013['club_name'].to_list()
list_clubsbundesliga2014 = bundesliga2014['club_name'].to_list()
list_clubsbundesliga2015 = bundesliga2015['club_name'].to_list()
list_clubsbundesliga2016 = bundesliga2016['club_name'].to_list()
list_clubsbundesliga2017 = bundesliga2017['club_name'].to_list()
list_clubsbundesliga2018 = bundesliga2018['club_name'].to_list()
list_clubsbundesliga2019 = bundesliga2019['club_name'].to_list()
list_clubsbundesliga2020 = bundesliga2020['club_name'].to_list()

list_age_bundesliga = []

list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2004, list_clubsbundesliga2004, 0))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2005, list_clubsbundesliga2005, 18))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2006, list_clubsbundesliga2006, 36))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2007, list_clubsbundesliga2007, 54))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2008, list_clubsbundesliga2008, 72))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2009, list_clubsbundesliga2009, 90))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2010, list_clubsbundesliga2010, 108))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2011, list_clubsbundesliga2011, 126))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2012, list_clubsbundesliga2012, 144))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2013, list_clubsbundesliga2013, 162))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2014, list_clubsbundesliga2014, 180))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2015, list_clubsbundesliga2015, 198))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2016, list_clubsbundesliga2016, 216))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2017, list_clubsbundesliga2017, 234))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2018, list_clubsbundesliga2018, 252))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2019, list_clubsbundesliga2019, 270))
list_age_bundesliga.append(age_bundesliga(bundesliga, bundesliga2020, list_clubsbundesliga2020, 288))

print(list_age_bundesliga)

#list => faire de list_age_bundesliga pas une liste de liste, mais une seule liste avec une fonction...
#bundesliga['Age'] = list
#bundesliga.to_csv('data/concat_years_age/bundesliga.csv', index=False)

[[5    25.555556
Name: age, dtype: float64, 9    25.64
Name: age, dtype: float64, 14    25.76
Name: age, dtype: float64, 12    23.545455
Name: age, dtype: float64, 15    23.6
Name: age, dtype: float64, 4    24.076923
Name: age, dtype: float64, 6    24.0
Name: age, dtype: float64, 10    23.903226
Name: age, dtype: float64, 17    24.263158
Name: age, dtype: float64, 11    25.815789
Name: age, dtype: float64, 2    25.380952
Name: age, dtype: float64, 0    26.793103
Name: age, dtype: float64, 3    23.785714
Name: age, dtype: float64, 1    26.733333
Name: age, dtype: float64, 7    28.194444
Name: age, dtype: float64, 16    25.375
Name: age, dtype: float64, 8    27.125
Name: age, dtype: float64, 13    23.4
Name: age, dtype: float64], [6    27.692308
Name: age, dtype: float64, 15    24.0
Name: age, dtype: float64, 11    23.387097
Name: age, dtype: float64, 10    23.857143
Name: age, dtype: float64, 5    22.5
Name: age, dtype: float64, 13    24.578947
Name: age, dtype: float64, 7    25.08
Name: age, dtype: float64, 2    25.428571
Name: age, dtype: float64, 16    24.62963
Name: age, dtype: float64, 8    26.756757
Name: age, dtype: float64, 3    26.6
Name: age, dtype: float64, 12    24.516129
Name: age, dtype: float64, 4    24.96875
Name: age, dtype: float64, 9    26.178571
Name: age, dtype: float64, 17    26.36
Name: age, dtype: float64, 1    25.2
Name: age, dtype: float64, 0    25.606061
Name: age, dtype: float64, 14    26.555556
Name: age, dtype: float64], [15    24.794118
Name: age, dtype: float64, 10    24.6
Name: age, dtype: float64, 14    23.333333
Name: age, dtype: float64, 5    25.571429
Name: age, dtype: float64, 4    23.8
Name: age, dtype: float64, 0    23.741935
Name: age, dtype: float64, 11    24.75
Name: age, dtype: float64, 16    25.4
Name: age, dtype: float64, 6    23.35
Name: age, dtype: float64, 13    23.230769
Name: age, dtype: float64, 12    24.791667
Name: age, dtype: float64, 3    24.681818
Name: age, dtype: float64, 9    25.083333
Name: age, dtype: float64, 8    24.941176
Name: age, dtype: float64, 17    25.136364
Name: age, dtype: float64, 1    25.0
Name: age, dtype: float64, 2    26.285714
Name: age, dtype: float64, 7    25.454545
Name: age, dtype: float64], [3    25.44
Name: age, dtype: float64, 14    22.5
Name: age, dtype: float64, 8    24.2
Name: age, dtype: float64, 9    22.551724
Name: age, dtype: float64, 17    25.125
Name: age, dtype: float64, 15    25.333333
Name: age, dtype: float64, 2    24.826087
Name: age, dtype: float64, 10    24.44
Name: age, dtype: float64, 5    25.3125
Name: age, dtype: float64, 11    23.833333
Name: age, dtype: float64, 12    24.941176
Name: age, dtype: float64, 16    26.323529
Name: age, dtype: float64, 4    26.142857
Name: age, dtype: float64, 6    25.1875
Name: age, dtype: float64, 1    25.666667
Name: age, dtype: float64, 0    26.37037
Name: age, dtype: float64, 7    25.217391
Name: age, dtype: float64, 13    27.060606
Name: age, dtype: float64], [17    26.073171
Name: age, dtype: float64, 3    26.444444
Name: age, dtype: float64, 15    24.392857
Name: age, dtype: float64, 11    23.0
Name: age, dtype: float64, 9    23.275862
Name: age, dtype: float64, 4    25.5
Name: age, dtype: float64, 14    24.5
Name: age, dtype: float64, 8    24.0
Name: age, dtype: float64, 2    23.785714
Name: age, dtype: float64, 13    22.842105
Name: age, dtype: float64, 10    26.380952
Name: age, dtype: float64, 0    24.653846
Name: age, dtype: float64, 6    24.785714
Name: age, dtype: float64, 16    26.272727
Name: age, dtype: float64, 5    26.166667
Name: age, dtype: float64, 7    23.83871
Name: age, dtype: float64, 12    25.636364
Name: age, dtype: float64, 1    26.096774
Name: age, dtype: float64], [4    25.0
Name: age, dtype: float64, 8    23.242424
Name: age, dtype: float64, 13    23.1875
Name: age, dtype: float64, 3    23.7
Name: age, dtype: float64, 5    23.772727
Name: age, dtype: float64, 15    23.75
Name: age, dtype: float64, 9    24.083333
Name: age, dtype: float64, 17    26.172414
Name: age, dtype: float64, 2    25.8
Name: age, dtype: float64, 7    23.26087
Name: age, dtype: float64, 14    22.15
Name: age, dtype: float64, 6    25.272727
Name: age, dtype: float64, 0    23.9
Name: age, dtype: float64, 12    23.136364
Name: age, dtype: float64, 10    26.315789
Name: age, dtype: float64, 1    23.166667
Name: age, dtype: float64, 16    25.761905
Name: age, dtype: float64, 11    26.064516
Name: age, dtype: float64], [6    23.375
Name: age, dtype: float64, 4    23.310345
Name: age, dtype: float64, 5    25.333333
Name: age, dtype: float64, 12    25.62963
Name: age, dtype: float64, 3    23.621622
Name: age, dtype: float64, 2    22.815789
Name: age, dtype: float64, 1    23.384615
Name: age, dtype: float64, 11    22.0
Name: age, dtype: float64, 13    23.076923
Name: age, dtype: float64, 0    23.451613
Name: age, dtype: float64, 15    22.419355
Name: age, dtype: float64, 16    25.821429
Name: age, dtype: float64, 14    22.962963
Name: age, dtype: float64, 9    24.375
Name: age, dtype: float64, 17    24.323529
Name: age, dtype: float64, 7    25.681818
Name: age, dtype: float64, 8    23.84
Name: age, dtype: float64, 10    26.5
Name: age, dtype: float64], [6    23.894737
Name: age, dtype: float64, 5    23.538462
Name: age, dtype: float64, 9    25.241379
Name: age, dtype: float64, 7    23.342105
Name: age, dtype: float64, 4    22.612903
Name: age, dtype: float64, 16    23.954545
Name: age, dtype: float64, 11    22.6875
Name: age, dtype: float64, 17    24.804348
Name: age, dtype: float64, 14    23.694444
Name: age, dtype: float64, 2    23.09375
Name: age, dtype: float64, 15    22.033333
Name: age, dtype: float64, 13    24.5
Name: age, dtype: float64, 3    24.324324
Name: age, dtype: float64, 8    23.72
Name: age, dtype: float64, 10    24.692308
Name: age, dtype: float64, 12    24.217391
Name: age, dtype: float64, 0    23.138889
Name: age, dtype: float64, 1    23.966667
Name: age, dtype: float64], [3    24.470588
Name: age, dtype: float64, 4    23.416667
Name: age, dtype: float64, 2    21.810811
Name: age, dtype: float64, 8    25.282051
Name: age, dtype: float64, 12    23.473684
Name: age, dtype: float64, 6    25.05
Name: age, dtype: float64, 10    23.857143
Name: age, dtype: float64, 5    22.32
Name: age, dtype: float64, 11    23.826087
Name: age, dtype: float64, 0    22.321429
Name: age, dtype: float64, 17    25.469388
Name: age, dtype: float64, 16    23.368421
Name: age, dtype: float64, 1    24.521739
Name: age, dtype: float64, 13    24.392857
Name: age, dtype: float64, 7    25.969697
Name: age, dtype: float64, 15    23.530612
Name: age, dtype: float64, 9    24.622222
Name: age, dtype: float64, 14    23.894737
Name: age, dtype: float64], [3    22.733333
Name: age, dtype: float64, 4    22.541667
Name: age, dtype: float64, 9    24.777778
Name: age, dtype: float64, 2    22.941176
Name: age, dtype: float64, 17    23.982759
Name: age, dtype: float64, 5    22.888889
Name: age, dtype: float64, 1    25.392857
Name: age, dtype: float64, 8    24.103448
Name: age, dtype: float64, 15    23.604167
Name: age, dtype: float64, 11    23.588235
Name: age, dtype: float64, 12    24.304348
Name: age, dtype: float64, 14    23.545455
Name: age, dtype: float64, 7    26.730769
Name: age, dtype: float64, 13    23.7
Name: age, dtype: float64, 16    24.090909
Name: age, dtype: float64, 10    23.090909
Name: age, dtype: float64, 0    22.171429
Name: age, dtype: float64, 6    24.05
Name: age, dtype: float64], [3    23.473684
Name: age, dtype: float64, 17    24.25
Name: age, dtype: float64, 5    22.894737
Name: age, dtype: float64, 2    21.888889
Name: age, dtype: float64, 7    23.827586
Name: age, dtype: float64, 8    24.04
Name: age, dtype: float64, 4    23.647059
Name: age, dtype: float64, 15    22.565217
Name: age, dtype: float64, 6    24.617647
Name: age, dtype: float64, 14    22.942857
Name: age, dtype: float64, 1    25.0
Name: age, dtype: float64, 0    23.703704
Name: age, dtype: float64, 10    24.0
Name: age, dtype: float64, 16    24.347826
Name: age, dtype: float64, 11    25.038462
Name: age, dtype: float64, 9    24.102564
Name: age, dtype: float64, 12    23.5625
Name: age, dtype: float64, 13    24.12
Name: age, dtype: float64], [3    24.35
Name: age, dtype: float64, 4    23.428571
Name: age, dtype: float64, 2    22.219512
Name: age, dtype: float64, 5    23.904762
Name: age, dtype: float64, 9    23.909091
Name: age, dtype: float64, 1    24.826087
Name: age, dtype: float64, 12    24.041667
Name: age, dtype: float64, 17    23.92
Name: age, dtype: float64, 0    25.111111
Name: age, dtype: float64, 10    23.894737
Name: age, dtype: float64, 8    26.333333
Name: age, dtype: float64, 7    24.625
Name: age, dtype: float64, 14    24.307692
Name: age, dtype: float64, 13    24.703704
Name: age, dtype: float64, 15    22.288136
Name: age, dtype: float64, 6    25.142857
Name: age, dtype: float64, 16    23.605263
Name: age, dtype: float64, 11    24.684211
Name: age, dtype: float64], [3    22.846154
Name: age, dtype: float64, 12    22.576923
Name: age, dtype: float64, 4    23.9
Name: age, dtype: float64, 16    22.979592
Name: age, dtype: float64, 0    24.157895
Name: age, dtype: float64, 11    25.529412
Name: age, dtype: float64, 13    23.323529
Name: age, dtype: float64, 15    24.461538
Name: age, dtype: float64, 5    22.875
Name: age, dtype: float64, 9    23.705882
Name: age, dtype: float64, 6    23.0
Name: age, dtype: float64, 2    22.447368
Name: age, dtype: float64, 7    25.903226
Name: age, dtype: float64, 10    24.057143
Name: age, dtype: float64, 1    24.71875
Name: age, dtype: float64, 17    23.846154
Name: age, dtype: float64, 8    23.55
Name: age, dtype: float64, 14    25.708333
Name: age, dtype: float64], [3    25.08
Name: age, dtype: float64, 8    24.238095
Name: age, dtype: float64, 15    22.487179
Name: age, dtype: float64, 4    23.166667
Name: age, dtype: float64, 2    22.875
Name: age, dtype: float64, 12    21.724138
Name: age, dtype: float64, 16    24.25
Name: age, dtype: float64, 6    23.166667
Name: age, dtype: float64, 5    21.913043
Name: age, dtype: float64, 11    22.789474
Name: age, dtype: float64, 14    24.647059
Name: age, dtype: float64, 7    25.064516
Name: age, dtype: float64, 10    23.571429
Name: age, dtype: float64, 1    24.575758
Name: age, dtype: float64, 13    23.16129
Name: age, dtype: float64, 17    23.585366
Name: age, dtype: float64, 9    22.935484
Name: age, dtype: float64, 0    24.066667
Name: age, dtype: float64], [3    24.533333
Name: age, dtype: float64, 4    24.193548
Name: age, dtype: float64, 12    22.0
Name: age, dtype: float64, 2    23.222222
Name: age, dtype: float64, 5    23.238095
Name: age, dtype: float64, 17    23.678571
Name: age, dtype: float64, 6    23.319149
Name: age, dtype: float64, 14    24.926829
Name: age, dtype: float64, 15    23.0
Name: age, dtype: float64, 9    24.05
Name: age, dtype: float64, 11    21.961538
Name: age, dtype: float64, 1    23.290323
Name: age, dtype: float64, 13    24.567568
Name: age, dtype: float64, 8    23.878788
Name: age, dtype: float64, 7    24.928571
Name: age, dtype: float64, 16    22.971429
Name: age, dtype: float64, 10    24.702703
Name: age, dtype: float64, 0    25.85
Name: age, dtype: float64], [4    25.0
Name: age, dtype: float64, 5    23.757576
Name: age, dtype: float64, 12    21.535714
Name: age, dtype: float64, 6    23.2
Name: age, dtype: float64, 3    22.526316
Name: age, dtype: float64, 16    24.659574
Name: age, dtype: float64, 17    23.413793
Name: age, dtype: float64, 13    23.466667
Name: age, dtype: float64, 7    23.918367
Name: age, dtype: float64, 11    22.290323
Name: age, dtype: float64, 1    23.717949
Name: age, dtype: float64, 9    24.166667
Name: age, dtype: float64, 2    24.129032
Name: age, dtype: float64, 0    22.277778
Name: age, dtype: float64, 8    24.974359
Name: age, dtype: float64, 15    23.40625
Name: age, dtype: float64, 10    24.4
Name: age, dtype: float64, 14    23.046512
Name: age, dtype: float64], [5    23.52
Name: age, dtype: float64, 12    20.833333
Name: age, dtype: float64, 6    23.590909
Name: age, dtype: float64, 17    23.72
Name: age, dtype: float64, 8    24.404762
Name: age, dtype: float64, 4    22.65
Name: age, dtype: float64, 1    24.340426
Name: age, dtype: float64, 7    22.333333
Name: age, dtype: float64, 16    23.172414
Name: age, dtype: float64, 13    24.935484
Name: age, dtype: float64, 15    23.83871
Name: age, dtype: float64, 2    23.586207
Name: age, dtype: float64, 9    25.178571
Name: age, dtype: float64, 11    23.861111
Name: age, dtype: float64, 3    23.580645
Name: age, dtype: float64, 0    24.825
Name: age, dtype: float64, 14    24.974359
Name: age, dtype: float64, 10    24.697674
Name: age, dtype: float64]]